export const CITY_META = {
  'sharm-el-sheikh': {
    name: 'Sharm El Sheikh',
    region: 'Red Sea',
    lat: 27.9158,
    lng: 34.3300,
    tagline: 'Red Sea diving capital — know before you go',
    intro: 'Sharm El Sheikh is Egypt\'s premier Red Sea resort town. A beautiful destination — but tourists overpay and get scammed daily. This guide gives you the real picture.',
  },
  hurghada: {
    name: 'Hurghada',
    region: 'Red Sea',
    lat: 27.2574,
    lng: 33.8129,
    tagline: 'Egypt\'s most visited resort — navigate it smart',
    intro: 'Hurghada draws millions of tourists each year. The beaches are stunning, the scams are rampant. Use this guide to pay fair prices and avoid the traps.',
  },
  luxor: {
    name: 'Luxor',
    region: 'Upper Egypt',
    lat: 25.6872,
    lng: 32.6396,
    tagline: 'The world\'s greatest open-air museum — on your terms',
    intro: 'Luxor contains more ancient history per square kilometer than anywhere on earth. It also has some of Egypt\'s most aggressive tourist touts. Know the difference.',
  },
  aswan: {
    name: 'Aswan',
    region: 'Upper Egypt',
    lat: 24.0889,
    lng: 32.8998,
    tagline: 'Nubian soul, Nile magic — no nonsense',
    intro: 'Aswan is Egypt\'s most relaxed city. The Nile is at its most beautiful here. Felucca captains will try to overcharge you — but now you know.',
  },
};

export const CITY_PRICES = {
  'sharm-el-sheikh': [
    { item: 'Airport taxi to Naama Bay', local: 80, fair: 150, scam: 500, note: 'Agree upfront. Use Uber/Careem if available.' },
    { item: 'Taxi within Naama Bay (short trip)', local: 30, fair: 60, scam: 200, note: 'Max 5km. Always negotiate before entering.' },
    { item: 'Taxi — Naama Bay to Old Market', local: 40, fair: 70, scam: 250, note: 'Agree price before getting in. 10 min drive.' },
    { item: 'Taxi — Naama Bay to Hadaba', local: 35, fair: 65, scam: 200, note: 'Short trip. Refuse anything above 100 EGP.' },
    { item: 'Taxi — Naama Bay to Sharks Bay', local: 50, fair: 90, scam: 280, note: 'Fixed price driver preferred.' },
    { item: 'Careem / Uber (short city trip)', local: 55, fair: 75, scam: 200, note: 'App price is fixed and transparent. Safest option.' },
    { item: 'Diving – 2 dives with equipment', local: 700, fair: 1100, scam: 2500, note: 'Book with PADI-certified centers only.' },
    { item: 'PADI Open Water course (4 days)', local: 3000, fair: 4500, scam: 9000, note: 'Includes certification, equipment, all dives.' },
    { item: 'Snorkeling day trip (boat + gear)', local: 300, fair: 500, scam: 1200, note: 'Includes boat, equipment, lunch at fair price.' },
    { item: 'Snorkeling gear rental (per day)', local: 60, fair: 100, scam: 300, note: 'Rent from dive center, not beach vendors.' },
    { item: 'Quad biking (1 hour)', local: 400, fair: 700, scam: 1800, note: 'Desert safaris are heavily inflated for tourists.' },
    { item: 'Desert safari – 4 hours (full)', local: 500, fair: 850, scam: 2200, note: 'Includes quad + camel + Bedouin tea at fair price.' },
    { item: 'Camel ride (30 min)', local: 100, fair: 180, scam: 600, note: 'Agree on price for the whole ride, not per photo.' },
    { item: 'Horse carriage – 1 hour city tour', local: 80, fair: 150, scam: 500, note: 'Negotiate round-trip price before departure.' },
    { item: 'Ras Mohammed park entry', local: 200, fair: 200, scam: 200, note: 'Fixed government price. No "special rate" exists.' },
    { item: 'Glass-bottom boat trip (2 hours)', local: 150, fair: 280, scam: 700, note: 'Book at marina. Not from beach touts.' },
    { item: 'Restaurant meal – mid-range', local: 120, fair: 200, scam: 600, note: 'Tourist strip prices are 2–3x higher.' },
    { item: 'Restaurant meal – local Egyptian', local: 60, fair: 90, scam: 300, note: 'Old Market area has fair local prices.' },
    { item: 'Shisha at café', local: 40, fair: 70, scam: 200, note: 'Naama Bay cafés charge 2–3x local area price.' },
    { item: 'Water (1.5L bottle)', local: 5, fair: 10, scam: 30, note: 'Buy from supermarkets, not beach vendors.' },
    { item: 'Fresh juice (large glass)', local: 20, fair: 35, scam: 100, note: 'Local juice stands near Old Market are cheapest.' },
    { item: 'Coffee at café (cappuccino)', local: 40, fair: 65, scam: 150, note: 'Naama Bay cafés at tourist-strip prices.' },
    { item: 'Hotel – budget per night', local: 400, fair: 600, scam: 1500, note: 'Hadaba and Old Market areas have best value.' },
    { item: 'Hotel – mid-range per night', local: 900, fair: 1400, scam: 3500, note: 'Book directly or via Booking.com for best rates.' },
    { item: 'Beach chair + umbrella (daily)', local: 50, fair: 80, scam: 250, note: 'Public beach access is free by law in Egypt.' },
    // SIM Cards — all operators
    { item: 'SIM card – Vodafone 10GB / 14 days', local: 110, fair: 130, scam: 400, note: 'Official Vodafone store only. Not airport kiosks.' },
    { item: 'SIM card – Vodafone 15GB / 30 days', local: 130, fair: 155, scam: 420, note: 'Best seller for 2–4 week stays. Official store.' },
    { item: 'SIM card – Vodafone 25GB / 30 days', local: 175, fair: 200, scam: 480, note: 'For remote workers or heavy data users.' },
    { item: 'SIM card – Orange 15GB / 30 days', local: 115, fair: 140, scam: 400, note: 'Orange store in Old Market area. Cheaper than Vodafone.' },
    { item: 'SIM card – Orange 25GB / 30 days', local: 160, fair: 185, scam: 450, note: 'Good value for extended stays.' },
    { item: 'SIM card – e& (Etisalat) 15GB / 30 days', local: 105, fair: 130, scam: 380, note: 'Cheapest 15GB option. Coverage slightly less than Vodafone.' },
    { item: 'SIM card – airport kiosk (any operator)', local: 130, fair: 130, scam: 450, note: 'Same SIM, 2–4x markup. Wait until the city.' },
  ],
  hurghada: [
    { item: 'Airport transfer to hotel zone', local: 80, fair: 150, scam: 500, note: 'Official taxi desk inside arrivals only.' },
    { item: 'Taxi – city center short trip', local: 30, fair: 60, scam: 200, note: 'El Dahar to Marina: max 80 EGP fair.' },
    { item: 'Taxi – El Dahar to Sahl Hasheesh', local: 80, fair: 130, scam: 400, note: '20km. Agree in EGP before getting in.' },
    { item: 'Taxi – Marina to airport', local: 80, fair: 150, scam: 450, note: 'Pre-book with hotel or use Careem.' },
    { item: 'Microbus (local bus – any route)', local: 5, fair: 8, scam: 50, note: 'Locals use this. Runs along the main coastal road.' },
    { item: 'Careem / Uber (short trip)', local: 50, fair: 70, scam: 200, note: 'Most reliable option. App price is fixed.' },
    { item: 'Glass-bottom boat trip (3 hrs)', local: 200, fair: 350, scam: 900, note: 'Book at the marina, not through hotel reception.' },
    { item: 'Giftun Island Day Trip (full day)', local: 250, fair: 450, scam: 1100, note: 'Includes lunch, snorkeling gear, boat. Fair price from marina.' },
    { item: 'Dolphin House boat trip', local: 250, fair: 450, scam: 1000, note: 'Morning departure from marina. Includes snorkeling.' },
    { item: 'Desert safari – 4 hours', local: 400, fair: 750, scam: 1800, note: 'Includes quad, camel, BBQ at fair price.' },
    { item: 'Quad bike rental (1 hour)', local: 250, fair: 400, scam: 1000, note: 'Confirm total price for your group. Not per person.' },
    { item: 'Parasailing (1 session)', local: 250, fair: 400, scam: 1000, note: 'Fixed price usually posted at the activity stand.' },
    { item: 'Snorkeling gear rental (per day)', local: 50, fair: 80, scam: 250, note: 'From marina dive centers. Check gear works before paying.' },
    { item: 'Diving – 2 dives with equipment', local: 600, fair: 1000, scam: 2200, note: 'PADI centers at marina have clear pricing boards.' },
    { item: 'PADI Open Water course', local: 2500, fair: 3800, scam: 7500, note: 'Always confirm certification is fully included.' },
    { item: 'Restaurant meal – local Egyptian', local: 80, fair: 140, scam: 400, note: 'El Dahar old town has genuine local pricing.' },
    { item: 'Restaurant meal – tourist strip', local: 150, fair: 250, scam: 700, note: 'Marina and Sahl Hasheesh restaurants are pricier.' },
    { item: 'Shisha at a café', local: 30, fair: 50, scam: 150, note: 'Tourist strip cafés charge 3–4x local price.' },
    { item: 'Coffee (cappuccino, café)', local: 35, fair: 55, scam: 120, note: 'Marina cafés charge tourist prices.' },
    { item: 'Water (1.5L bottle)', local: 5, fair: 10, scam: 30, note: 'Supermarket price. Resort/beach vendors charge 4–5x.' },
    { item: 'Fresh juice (large)', local: 20, fair: 35, scam: 100, note: 'Juice bars in El Dahar are excellent value.' },
    { item: 'Hotel – budget per night', local: 350, fair: 550, scam: 1200, note: 'El Dahar area has the cheapest accommodation.' },
    { item: 'Hotel – mid-range per night', local: 800, fair: 1300, scam: 3000, note: 'Sahl Hasheesh mid-range options give best value.' },
    { item: 'Beach chair + umbrella (daily)', local: 40, fair: 70, scam: 200, note: 'Some public beaches are free by Egyptian law.' },
    // SIM Cards — all operators
    { item: 'SIM card – Vodafone 10GB / 14 days', local: 110, fair: 130, scam: 380, note: 'Official Vodafone store on Sahl Hasheesh Road.' },
    { item: 'SIM card – Vodafone 15GB / 30 days', local: 130, fair: 155, scam: 420, note: 'Best seller. 4G works well along coast.' },
    { item: 'SIM card – Vodafone 25GB / 30 days', local: 175, fair: 200, scam: 480, note: 'For digital nomads. Reliable hotspot speeds.' },
    { item: 'SIM card – Vodafone 40GB / 30 days', local: 250, fair: 275, scam: 550, note: 'Power user package. Unlimited local calls included.' },
    { item: 'SIM card – Orange 15GB / 30 days', local: 115, fair: 140, scam: 400, note: 'Orange store Marina Road. Cheaper than Vodafone.' },
    { item: 'SIM card – Orange 25GB / 30 days', local: 160, fair: 185, scam: 450, note: 'Good coverage along coastal highway.' },
    { item: 'SIM card – e& (Etisalat) 15GB / 30 days', local: 105, fair: 125, scam: 360, note: 'Cheapest 15GB in Egypt. Coverage OK in Hurghada center.' },
    { item: 'SIM card – e& 50GB / 30 days', local: 210, fair: 235, scam: 500, note: 'Best per-GB value. Best for remote workers on a budget.' },
    { item: 'SIM card – airport kiosk markup', local: 130, fair: 130, scam: 450, note: 'Identical SIM, inflated price. Always buy in the city.' },
  ],
  luxor: [
    { item: 'Taxi – airport to West Bank', local: 60, fair: 120, scam: 400, note: 'Negotiate before getting in. Fixed fare is standard.' },
    { item: 'Taxi – city center trip (East Bank)', local: 40, fair: 80, scam: 300, note: 'Never accept USD quotes. Always negotiate in EGP.' },
    { item: 'Taxi – East Bank to West Bank (road)', local: 80, fair: 150, scam: 500, note: 'Longer bridge route. Compare to 5 EGP ferry.' },
    { item: 'Taxi – full day with driver (West Bank)', local: 400, fair: 600, scam: 1800, note: 'Agree on EGP total, all temples included. 8 hours.' },
    { item: 'Local ferry – East to West Bank', local: 5, fair: 5, scam: 50, note: 'Government ferry. Runs every 30 min. Fixed 5 EGP.' },
    { item: 'Bicycle rental (West Bank, per day)', local: 80, fair: 120, scam: 300, note: 'Rent from guesthouses near ferry landing.' },
    { item: 'Calèche horse carriage (1 hour)', local: 80, fair: 150, scam: 500, note: 'Agree on price BEFORE getting in. Round trip.' },
    { item: 'Felucca – 2 hours on Nile', local: 100, fair: 200, scam: 600, note: 'Negotiate per hour, not per person.' },
    { item: 'Hot air balloon (certified, 1 hour)', local: 1200, fair: 1800, scam: 4000, note: 'Only book ECAA-certified operators. Fatalities from uncertified.' },
    { item: 'Private Egyptologist guide (full day)', local: 800, fair: 1200, scam: 3000, note: 'Government-licensed guides carry official badge.' },
    { item: 'Half-day private guide (4 hours)', local: 500, fair: 750, scam: 2000, note: 'East or West Bank only. Ask for government ID badge.' },
    { item: 'Valley of the Kings ticket (3 tombs)', local: 360, fair: 360, scam: 360, note: 'Fixed government price. No "special rate" exists.' },
    { item: 'Tutankhamun tomb extra ticket', local: 300, fair: 300, scam: 300, note: 'Fixed add-on at the Valley. Worth every pound.' },
    { item: 'Karnak Temple ticket', local: 300, fair: 300, scam: 300, note: 'Fixed government price. Includes Sound & Light show separately.' },
    { item: 'Luxor Temple ticket', local: 200, fair: 200, scam: 200, note: 'Fixed price. Night visit is spectacular.' },
    { item: 'Medinet Habu ticket', local: 180, fair: 180, scam: 180, note: 'Fixed price. Less crowded than Karnak.' },
    { item: 'Valley of the Queens ticket', local: 180, fair: 180, scam: 180, note: 'Fixed government price. Nefertari tomb costs extra.' },
    { item: 'Nefertari tomb extra ticket', local: 1400, fair: 1400, scam: 1400, note: 'Pricey but extraordinary. Limit of 150 visitors/day.' },
    { item: 'Luxor Museum ticket', local: 200, fair: 200, scam: 200, note: 'Fixed price. World-class collection. Very worthwhile.' },
    { item: 'Karnak Sound & Light show', local: 250, fair: 250, scam: 250, note: 'Fixed evening price. Worth attending once.' },
    { item: 'Restaurant meal – local', local: 80, fair: 130, scam: 400, note: 'East Bank near train station has honest local spots.' },
    { item: 'Restaurant meal – tourist', local: 150, fair: 250, scam: 700, note: 'Corniche restaurants charge tourist prices.' },
    { item: 'Hotel – budget per night', local: 300, fair: 500, scam: 1200, note: 'West Bank guesthouses are excellent value.' },
    { item: 'Hotel – mid-range per night', local: 700, fair: 1100, scam: 2500, note: 'East Bank Corniche hotels have Nile views.' },
    { item: 'Water (1.5L bottle)', local: 5, fair: 8, scam: 25, note: 'Temple souvenir shops charge up to 30 EGP.' },
    { item: 'Train – Luxor to Cairo (2nd class)', local: 200, fair: 350, scam: 1000, note: 'Official Luxor station ticket window only.' },
    { item: 'Train – Luxor to Aswan (2nd class)', local: 60, fair: 100, scam: 350, note: '2–3 hours. Scenic Nile Valley route.' },
    // SIM Cards — all operators
    { item: 'SIM card – Vodafone 15GB / 30 days', local: 130, fair: 155, scam: 400, note: 'Vodafone on Luxor Temple Road. Best coverage at temples.' },
    { item: 'SIM card – Orange 15GB / 30 days', local: 115, fair: 140, scam: 380, note: 'Orange Corniche store. Good coverage on East Bank.' },
    { item: 'SIM card – e& (Etisalat) 15GB / 30 days', local: 105, fair: 125, scam: 360, note: 'Cheapest option. Coverage adequate in central Luxor.' },
    { item: 'SIM card – airport/station kiosk', local: 130, fair: 130, scam: 430, note: 'Heavily marked up. Buy from the official stores in town.' },
  ],
  aswan: [
    { item: 'Felucca – per hour (whole boat)', local: 80, fair: 150, scam: 500, note: 'Standard rate for the entire boat, not per person.' },
    { item: 'Felucca – 2 hour sunset trip (whole boat)', local: 160, fair: 280, scam: 700, note: 'Specify 2 hours AND whole boat. Pay after landing.' },
    { item: 'Felucca – Nubian Village round trip', local: 200, fair: 320, scam: 800, note: 'Includes return. Agree on both directions upfront.' },
    { item: 'Abu Simbel day trip – shared bus/convoy', local: 400, fair: 600, scam: 1500, note: 'Book through reputable operators. 3-hr drive each way.' },
    { item: 'Abu Simbel – private car (full service)', local: 900, fair: 1300, scam: 3000, note: 'For groups of 4+. Split cost per person.' },
    { item: 'Nubian Village boat trip (return)', local: 100, fair: 200, scam: 600, note: 'Includes return boat. Do not pay per person.' },
    { item: 'Nile motor boat (Corniche crossing)', local: 5, fair: 10, scam: 50, note: 'Cross to Elephantine Island. Agree per trip.' },
    { item: 'Philae Temple ticket', local: 180, fair: 180, scam: 180, note: 'Fixed government price. Boat to island: ~40 EGP.' },
    { item: 'Abu Simbel temple ticket', local: 360, fair: 360, scam: 360, note: 'Fixed government price at the site.' },
    { item: 'Aswan High Dam entry', local: 80, fair: 80, scam: 80, note: 'Fixed ticket price. Foreigners pay same as locals.' },
    { item: 'Aswan Botanical Garden (Kitchener Island)', local: 50, fair: 50, scam: 50, note: 'Fixed price. Take motorboat from Corniche (~15 EGP).' },
    { item: 'Sound & Light show – Philae', local: 250, fair: 250, scam: 250, note: 'Fixed price. Evening show is spectacular.' },
    { item: 'Nubian Museum entry', local: 150, fair: 150, scam: 150, note: 'Fixed price. World-class collection of Nubian artifacts.' },
    { item: 'Taxi – airport to city center', local: 50, fair: 100, scam: 350, note: 'Short distance. Do not pay more than 120 EGP.' },
    { item: 'Taxi – city center short trip', local: 30, fair: 55, scam: 180, note: 'Aswan is compact. Most trips under 70 EGP.' },
    { item: 'Restaurant meal – local', local: 60, fair: 120, scam: 350, note: 'Aswan is cheaper than Luxor and Cairo.' },
    { item: 'Restaurant meal – Corniche tourist', local: 120, fair: 200, scam: 500, note: 'Nile-view restaurants add view premium.' },
    { item: 'Nubian souvenir – handmade', local: 50, fair: 100, scam: 300, note: 'Bargaining is expected but stay respectful.' },
    { item: 'Hotel – budget per night', local: 250, fair: 400, scam: 1000, note: 'Corniche guesthouses offer great Nile views cheaply.' },
    { item: 'Hotel – mid-range per night', local: 600, fair: 900, scam: 2200, note: 'Sofitel Old Cataract is luxury historic option.' },
    { item: 'Water (1.5L bottle)', local: 5, fair: 8, scam: 25, note: 'Supermarket on Corniche has best prices.' },
    { item: 'Camel ride (30 min near West Bank)', local: 80, fair: 150, scam: 500, note: 'Agree on total price before mounting.' },
    { item: 'Train – Aswan to Luxor (2nd class)', local: 60, fair: 80, scam: 300, note: 'Official train ticket only. 2–3 hour journey.' },
    { item: 'Train – Aswan to Cairo (1st class, night)', local: 400, fair: 600, scam: 1500, note: 'Overnight sleeper available. Book in advance.' },
    // SIM Cards — all operators
    { item: 'SIM card – Vodafone 15GB / 30 days', local: 130, fair: 155, scam: 400, note: 'Vodafone Corniche store. Good coverage in central Aswan.' },
    { item: 'SIM card – Vodafone 25GB / 30 days', local: 175, fair: 200, scam: 460, note: 'Recommended if visiting Abu Simbel — best remote coverage.' },
    { item: 'SIM card – Orange 15GB / 30 days', local: 115, fair: 140, scam: 380, note: 'Orange on Corniche. Solid coverage in city center.' },
    { item: 'SIM card – e& (Etisalat) 15GB / 30 days', local: 105, fair: 125, scam: 360, note: 'Cheapest. Coverage OK in Aswan center, weaker near Nubian villages.' },
    { item: 'SIM card – WE 15GB / 30 days', local: 95, fair: 110, scam: 320, note: 'Cheapest of all. Slower 4G speeds. Not recommended for heavy use.' },
    { item: 'SIM card – airport/station kiosk markup', local: 130, fair: 130, scam: 430, note: 'Buy from official stores on Corniche — same SIM, much cheaper.' },
  ],
};

export const CITY_SCAMS = {
  'sharm-el-sheikh': [
    { title: 'Airport "Helper" Baggage Scam', severity: 'high', desc: 'Men in unofficial vests offer to help with luggage at arrivals. They carry your bags 10 meters and demand 100–200 EGP tip aggressively.', avoid: 'Refuse all unsolicited help. Carry your own bags or use the official trolleys.' },
    { title: 'Taxi No Meter / Price Change On Arrival', severity: 'high', desc: 'Driver agrees on a price, then claims traffic, extra distance, or different zone to demand more on arrival.', avoid: 'Screenshot or photo the agreed price negotiation. Use Uber/Careem for fixed fares.' },
    { title: 'Fake Snorkeling Gear Swap', severity: 'high', desc: 'Vendor gives you working snorkel gear, replaces it with broken equipment after entering the water, then charges "damage fee" of 500+ EGP.', avoid: 'Rent only from dive centers with printed pricing boards.' },
    { title: 'Excursion Add-On Trap on Boats', severity: 'high', desc: 'You book a snorkeling trip for 200 EGP. On the boat, crew adds "optional" paid stops, photos, and food — real cost becomes 700+ EGP.', avoid: 'Ask for FULL itemized pricing in writing before boarding. "All inclusive" means nothing unless specified.' },
    { title: 'Fake Perfume Factory Tour', severity: 'medium', desc: 'A friendly local offers to show you a famous perfume factory. This is a high-pressure sales trap — exit is blocked until you buy.', avoid: 'Decline all unsolicited "free tours" or "factory visits." Always.' },
    { title: 'Free Gift Papyrus Scam', severity: 'medium', desc: 'Tourist handed a "free gift" of a small drawing or papyrus. Once accepted, vendor demands 300–500 EGP payment aggressively.', avoid: 'Never accept items from strangers near tourist sites. "Free" does not exist in tourist markets.' },
    { title: 'Diving Equipment Insurance Scam', severity: 'medium', desc: 'Dive center charges 200–400 EGP "mandatory insurance" for equipment that doesn\'t exist as a real policy.', avoid: 'Only pay what\'s on the official price board. Ask for an itemized receipt before paying.' },
    { title: 'Hotel "Special Price" Street Tout', severity: 'medium', desc: 'Street agent claims your hotel is overpriced and offers a "better hotel" for less. Collects deposit and delivers an inferior room.', avoid: 'Only book hotels through official sites. Never give deposits to street agents.' },
    { title: 'Restaurant Bill Padding', severity: 'medium', desc: 'Bill includes cover charge, bread fee, service charge, and additional items you didn\'t order. Can add 40–100% to the bill.', avoid: 'Ask for itemized menu with prices before ordering. Check every line of the bill.' },
    { title: 'Money Exchange Shortchange', severity: 'high', desc: 'Exchange bureaus count money quickly, deliver the wrong amount, and exploit tourist confusion about Egyptian notes.', avoid: 'Count every note yourself, slowly, in front of the cashier. Never rush.' },
    { title: 'Camel Ride Price Switch', severity: 'medium', desc: 'Camel owner quotes 50 EGP for a "short ride." Ride lasts 30 seconds. Demands 500 EGP to help you dismount.', avoid: 'Agree on the full round-trip price including dismounting before getting on.' },
    { title: 'Fake Police Officer "Fine"', severity: 'high', desc: 'Man in plain clothes claims to be tourist police, claims you violated a photography rule, and demands immediate fine payment.', avoid: 'Real tourist police have official uniforms and IDs. Never pay fines to individuals. Call 126.' },
    { title: 'SIM Card Overcharge at Airport Kiosk', severity: 'medium', desc: 'Airport SIM kiosks sell 15GB Vodafone/Orange SIMs for 380–450 EGP. The same SIM costs 115–130 EGP at official stores in town.', avoid: 'Wait until you reach Naama Bay or Old Market to buy a SIM from an official branded store.' },
    { title: 'Quad Bike Hidden Damage Fee', severity: 'medium', desc: 'Operator claims minor sand scratches on the quad require 500–1,000 EGP repair fee after your ride.', avoid: 'Photograph the quad from all angles BEFORE you drive it. Use certified operators with written damage policy.' },
    { title: '"Free" Boat Ride to Neighboring Beach', severity: 'medium', desc: 'Boatman offers a short "complimentary" trip to a quieter beach. On return, demands 300–500 EGP.', avoid: 'Never board any vessel without an agreed price. "Free" boat rides do not exist.' },
  ],
  hurghada: [
    { title: 'Airport Transfer Fake "Official" Drivers', severity: 'high', desc: 'Drivers outside arrivals claiming to be "official" charge 400–600 EGP for 150 EGP trips. They hold signs, wear vests — none are official.', avoid: 'Use the official taxi desk INSIDE the arrivals hall. The sign says "Official Taxi."' },
    { title: 'Money Exchange Shortchange', severity: 'high', desc: 'Exchange bureaus in El Dahar count money quickly and deliberately give wrong amount, banking on tourist confusion with EGP notes.', avoid: 'Count every note on the spot, in front of them. Never rush for any reason.' },
    { title: 'Per-Person Quad Bike Scam', severity: 'medium', desc: 'Quote given "per quad bike." On arrival it\'s "per person per quad," doubling or tripling the price.', avoid: 'Get total price for your exact group in writing before agreeing to anything.' },
    { title: 'Hotel "Upgrade" Street Agents', severity: 'medium', desc: 'Street agents offer hotel upgrades or cheaper rooms. Take deposit, disappear, or deliver a very different room.', avoid: 'Only book through official hotel websites or verified OTAs like Booking.com.' },
    { title: 'Restaurant Service Charge Ambush', severity: 'low', desc: 'Bill includes unexplained service charges, bread charges, and cover charges not on the menu, adding 30–50%.', avoid: 'Ask for the menu with prices BEFORE sitting. Request itemized bill before paying.' },
    { title: 'Boat Trip Photo Extortion', severity: 'medium', desc: 'Boat crew photographer takes hundreds of photos of you during snorkeling. At the end demands 800–1,200 EGP for the photos or they "delete" them publicly.', avoid: 'Refuse photos from boat crew photographers or agree on a fixed price at the start.' },
    { title: 'Fake Tour Guide Near Marina', severity: 'medium', desc: '"Official marina guide" approaches tourists and offers to organize trips. Not official — earns commission from operators who pay highest kickbacks.', avoid: 'Book at the marina ticket offices with posted prices, not from approaching individuals.' },
    { title: 'SIM Card Airport Kiosk Scam', severity: 'medium', desc: 'Airport kiosks sell 15GB SIMs for 380–450 EGP. Same Vodafone or Orange card costs 115–130 EGP at official stores in the city.', avoid: 'Wait until you reach the city. Buy at an official branded Vodafone, Orange, or e& store only.' },
    { title: 'All-Inclusive Excursion Markup', severity: 'medium', desc: 'Hotel reception books excursions at 2–3x the marina price, claiming it\'s "guaranteed" or "safer."', avoid: 'Book all excursions yourself at the marina or through verified local operators.' },
    { title: 'Friendly Local Restaurant Commission', severity: 'medium', desc: 'A "helpful" local offers to take you to a "great local restaurant." Restaurant pays him 20–30% commission, added to your bill.', avoid: 'Find restaurants yourself. Any unsolicited recommendation to a restaurant is a commission play.' },
    { title: 'Parasailing Hidden Fees', severity: 'medium', desc: 'Quoted 400 EGP. On return, additional fees for "life jacket rental," "insurance," and "video" add 400–600 EGP more.', avoid: 'Ask for the total all-inclusive price in writing on a receipt before the activity starts.' },
    { title: 'Dolphin House Fake Tickets', severity: 'high', desc: 'Touts near the marina sell fake Dolphin House tour tickets for 300 EGP. The tickets are worthless — no boat accepts them.', avoid: 'Only buy from the marina ticket office with a physical printed receipt.' },
    { title: 'Snorkeling Gear Damage Scam', severity: 'medium', desc: 'Rental shop claims you damaged their mask or fins and demands 500–1,500 EGP. Equipment was already broken when rented.', avoid: 'Inspect and photograph all rental gear before taking it. Note any damage on the rental form.' },
    { title: '"Special" Massage / Spa Price Bait', severity: 'medium', desc: 'Quoted 200 EGP for a massage. Bill arrives for 800 EGP with undisclosed extras, oils, and "deep tissue supplement."', avoid: 'Confirm total price for the exact service you want. Read the full menu before agreeing.' },
  ],
  luxor: [
    { title: 'Self-Appointed Temple Guide Extortion', severity: 'high', desc: 'A man near the temple entrance offers to "help" with tickets or explain history. At the end demands 800–1,500 EGP for the unsolicited service.', avoid: 'Hire official guides (government badge) before entering, not at the gate. Say "La, shukran" firmly.' },
    { title: 'Hot Air Balloon Safety Scam', severity: 'high', desc: 'Operators with no ECAA certification offer cheap balloon rides (800–1,000 EGP). Several have crashed with fatalities.', avoid: 'ONLY book ECAA-certified operators. Never book balloons from hotel reception or street touts.' },
    { title: 'Alabaster Factory Kidnapping', severity: 'high', desc: '"Educational visit" to an alabaster factory becomes an aggressive sales pitch with guides blocking exits until you buy. Duration: 1–2 hours of pressure.', avoid: 'Say no to all unsolicited factory or workshop visits. If you enter, you can always leave — push through.' },
    { title: 'Taxi USD Confusion', severity: 'medium', desc: 'Taxi driver quotes price in "dollars" that actually means Egyptian Pounds, or vice versa — deliberately exploiting currency confusion.', avoid: 'Always say "EGP" or "Guinee masry" (Egyptian pound) explicitly before agreeing.' },
    { title: 'Carriage Driver Route Inflation', severity: 'medium', desc: 'Carriage takes much longer route than needed, then charges for distance traveled instead of the agreed destination.', avoid: 'Agree on price AND destination clearly with a map. Set time limit, not just destination.' },
    { title: 'Ticket Tout Near Valley of Kings', severity: 'high', desc: 'Tout offers to buy your tickets for you at a "discount." Tickets are either fake or bought at student price — you risk being turned away at the gate.', avoid: 'Buy all temple tickets yourself at the official booths only. Never from individuals.' },
    { title: 'Ferry Extra Charge', severity: 'low', desc: 'The local ferry costs 5 EGP. Boats claim the price is 50 EGP for foreigners, or try to take you on a "private boat" at inflated prices.', avoid: 'Use only the government passenger ferry on the marked dock. Price is 5 EGP, non-negotiable.' },
    { title: 'Fake Antique Sales', severity: 'medium', desc: 'Vendors near temples sell "genuine ancient artifacts" for 500–2,000 EGP. All are modern reproductions. Buying real antiques is also illegal in Egypt.', avoid: 'Never purchase "ancient artifacts." They are all fakes. Real antiquities export is a serious crime.' },
    { title: 'Horse Carriage No-Return Scam', severity: 'medium', desc: 'You hire a carriage for a round trip. At the destination, driver demands double for the return, claiming the original price was one-way only.', avoid: 'Specify "round trip" (rayih w gai) clearly and pay only after full return to starting point.' },
    { title: 'Fake Police Documentation Scam', severity: 'medium', desc: 'Man claims to be undercover police, asks to see your camera photos, claims you took photos of restricted area, demands "fine."', avoid: 'Real tourist police wear uniforms. Never pay informal fines. Call 126 immediately.' },
    { title: 'Restaurant "Closed for Private Event"', severity: 'medium', desc: 'Boy approaches outside a real restaurant and says it\'s closed, then redirects to cousin\'s restaurant which charges 3x the price.', avoid: 'Walk past the "helper" and check the restaurant yourself. If door is locked, it\'s closed.' },
    { title: 'West Bank Unofficial "Guard" Toll', severity: 'medium', desc: 'Men near tomb sites or desert areas demand payment for "permission" to enter or pass through an area.', avoid: 'Only pay fees at official staffed, signed, uniformed government booths. Ignore all others.' },
    { title: 'Papyrus Quality Scam', severity: 'low', desc: 'Vendor sells "real papyrus" paintings for 500–1,500 EGP. Most are banana leaf paper painted to look like papyrus. Test: real papyrus can be folded without cracking.', avoid: 'Only buy from reputable papyrus institutes with the fold test demonstration.' },
    { title: 'Midnight Luggage Storage Fee', severity: 'low', desc: 'Hotel claims you must pay 200–400 EGP "luggage storage" fee on checkout day if you want to leave bags until evening flight.', avoid: 'Confirm luggage storage policy and price at check-in, not on checkout day.' },
  ],
  aswan: [
    { title: 'Felucca Captain Bait & Switch', severity: 'high', desc: 'Captain quotes per-boat price (150 EGP/hour). At the boat, he reveals it\'s "per person per hour" — 4 people suddenly pay 600 EGP/hour.', avoid: 'Confirm "for the whole boat, not per person" — say it explicitly and verify before boarding.' },
    { title: 'Nubian Village Entry Fee Scam', severity: 'medium', desc: 'Men at the boat landing claim there\'s an entry fee for the Nubian village (100–200 EGP). No such official fee exists.', avoid: 'Nubian villages are free to visit. Pay for services or crafts voluntarily. No entry fee.' },
    { title: 'Abu Simbel Private Car Drop-Off', severity: 'medium', desc: 'Driver offers private car to Abu Simbel at premium price, then drops you 5km from the site claiming the road is blocked.', avoid: 'Use only reputable tour operators for Abu Simbel. Official convoy is the safest option.' },
    { title: 'Fake Police Checkpoint Toll', severity: 'medium', desc: 'Men in unofficial uniforms near temples demand a "toll" or "entry fee" for passing through or entering an area.', avoid: 'Only pay official fees at signed government booths. Report fake checkpoints to tourist police (126).' },
    { title: 'Souvenir Handed Gift Pressure', severity: 'medium', desc: 'In Nubian villages and markets, items pushed into hands unsolicited, then aggressive demands for payment follow.', avoid: 'Only enter shops you chose. Never accept hand-delivered items. "La shukran" firmly.' },
    { title: 'Felucca Sunset Trip Price Inflation', severity: 'medium', desc: 'Quoted 100 EGP "for a short ride." Ride takes 20 minutes, captain claims agreed price was for 2 hours, demands 500 EGP.', avoid: 'Specify exact duration AND price before boarding. "Two hours, whole boat, 200 EGP total."' },
    { title: 'Hotel Commission Touts at Train Station', severity: 'medium', desc: 'Men at Aswan train station offer "good cheap hotel" and earn 30–50% commission from the hotel, added to your room rate.', avoid: 'Pre-book your hotel. Decline all unsolicited hotel recommendations at transport hubs.' },
    { title: 'Elephant Island Boat Scam', severity: 'low', desc: 'Private boatmen near Elephantine Island charge 50–100 EGP for a 5 EGP government boat crossing.', avoid: 'Use only the government motorboat from the official dock on the Corniche. 5–10 EGP fixed.' },
    { title: 'Juice Bar Price Switch', severity: 'low', desc: 'Juice quoted at 20 EGP. After drinking, vendor claims 80 EGP because it was "special mango" or "large size."', avoid: 'Confirm exact price for exact drink before ordering. Point to the item and ask "bikam?" (how much?).' },
    { title: 'Abu Simbel Ticket Resale Scam', severity: 'medium', desc: 'Near Abu Simbel entrance, touts offer to buy tickets for you at "discount." Tickets are fake or forged.', avoid: 'Buy only at the official ticket booth at Abu Simbel. No middlemen, ever.' },
    { title: 'Crocodile Museum "Free Visit"', severity: 'low', desc: 'Guide offers free visit to Nubian crocodile house. At exit, large "crocodile feeding fee" demanded aggressively.', avoid: 'Ask about ALL costs before entering any "free" attraction. Walk away if costs not disclosed upfront.' },
    { title: 'Train Ticket Unofficial "Agent"', severity: 'medium', desc: 'Man at the station offers to buy train tickets for you "in queue" at the price of the ticket plus 100–200 EGP "service fee."', avoid: 'Buy all train tickets yourself at the official ticket windows inside the station.' },
    { title: 'Philae Temple Boat Extra Charge', severity: 'medium', desc: 'Captain claims the official Philae boat is not included in the temple ticket and charges 100–200 EGP per person.', avoid: 'The motorboat to Philae Island IS included in the official ticket. Do not pay separately.' },
    { title: 'Abu Simbel "Guide" Extortion', severity: 'medium', desc: 'A man at Abu Simbel offers "explanation" for the temples. After 10 minutes demands 500 EGP for the "tour."', avoid: 'Hire a guide BEFORE the site or bring your own research. Refuse all unsolicited on-site "helpers."' },
  ],
};

export const CITY_FAQS = {
  'sharm-el-sheikh': [
    { q: 'Is Sharm El Sheikh safe for tourists?', a: 'Yes. Sharm El Sheikh is heavily secured by Egyptian authorities. Violent crime against tourists is extremely rare. The main risks are petty scams and overcharging.' },
    { q: 'What is the fair taxi price from Sharm airport?', a: 'Fair tourist price: 150–200 EGP to Naama Bay. Anything above 250 EGP is overcharging. Use the official taxi desk inside arrivals.' },
    { q: 'Do I need a visa for Sharm El Sheikh?', a: 'Most nationalities get a free 15-day Sinai-only visa at Sharm airport. For rest of Egypt, full visa on arrival is $25 USD or eVisa in advance.' },
    { q: 'What is the best time to visit Sharm El Sheikh?', a: 'October to April: 20–28°C, ideal. June–August: 40°C+, cheapest but very hot. Diving visibility is excellent year-round.' },
    { q: 'Can I drink tap water in Sharm El Sheikh?', a: 'Never. Buy sealed bottled water only — 5 EGP at supermarket, not 30 EGP from a beach vendor.' },
    { q: 'Which SIM card should I buy in Sharm El Sheikh?', a: 'Vodafone has the best 4G coverage in Sharm. Buy a 15GB card (130 EGP) at the official Vodafone store in Naama Bay Mall. Orange is slightly cheaper and also reliable. Never buy at the airport kiosk — same SIM costs 380–450 EGP there.' },
    { q: 'Is scuba diving safe in Sharm El Sheikh?', a: 'Yes, with PADI-certified operators. Sharm is one of the world\'s top diving destinations. Avoid any dive center without a visible PADI certification and proper equipment safety checks.' },
    { q: 'Can I walk around Naama Bay at night?', a: 'Yes — Naama Bay is well-lit, patrolled, and safe to walk at night. It\'s one of the safest tourist areas in Egypt after dark. Side streets after midnight: use Careem instead of walking.' },
    { q: 'What is the Ras Mohammed National Park?', a: 'A protected marine national park south of Sharm — the best snorkeling and diving in Sinai. Entry is 200 EGP fixed fee. Day trips from Naama Bay cost 500–700 EGP all-inclusive.' },
    { q: 'Should I tip in Sharm El Sheikh?', a: 'Yes. Tipping is expected. 10–15% at restaurants, 20–50 EGP for hotel staff, 50–100 EGP for guides. Have small bills ready.' },
  ],
  hurghada: [
    { q: 'Is Hurghada worth visiting?', a: 'Yes — excellent beaches, world-class diving, affordable prices IF you know what you\'re doing. This guide exists because most tourists significantly overpay.' },
    { q: 'What is the fair price for a taxi in Hurghada?', a: 'Short trips within Hurghada: 50–80 EGP. Airport to hotel: 120–180 EGP. Never pay more than 300 EGP for any in-town trip.' },
    { q: 'Is Hurghada safe at night?', a: 'Sahl Hasheesh and Marina areas are well-lit and safe. El Dahar old town is fine but use normal caution after midnight.' },
    { q: 'Which SIM card is best in Hurghada?', a: 'Vodafone offers the best 4G coverage along the coastal highway and at dive sites. Orange is 10–15% cheaper with comparable coverage. e& (Etisalat) is cheapest but coverage is weaker offshore. Buy at official stores — NOT the airport kiosk (same SIM, 3x the price).' },
    { q: 'Is Hurghada good for families?', a: 'Extremely. Most resorts are all-inclusive with kids\' clubs, shallow pools, and calm beaches.' },
    { q: 'What is the Dolphin House in Hurghada?', a: 'A shallow reef 90 minutes from Hurghada marina where wild spinner dolphins gather. One of the best wildlife snorkeling experiences in Egypt. Costs 350–500 EGP from marina. Book directly at the marina ticket office — NOT from touts.' },
    { q: 'Can I buy alcohol in Hurghada?', a: 'Yes. Hurghada has bars, nightclubs, and supermarkets selling alcohol. Duty-free shops at the airport sell liquor at the best prices. Most restaurants outside all-inclusive resorts serve beer and wine.' },
    { q: 'What is Sahl Hasheesh?', a: 'A purpose-built resort area 18km south of central Hurghada. Very upscale, controlled access, quieter than Marina. Best choice for families and those wanting a peaceful premium beach holiday.' },
    { q: 'How far is Hurghada from Cairo?', a: '460km. About 5–6 hours by road. Flights exist (1 hour, 600–1,200 EGP) but buses (200–300 EGP) and shared cars are much cheaper.' },
    { q: 'Is kite surfing available in Hurghada?', a: 'Yes. The strong steady winds make Hurghada (specifically Kite Beach) one of the best kitesurfing spots in the world. Lessons: 600–900 EGP per session. Equipment rental: 300–500 EGP per day.' },
  ],
  luxor: [
    { q: 'How many days do you need in Luxor?', a: 'Minimum 2 days for East and West Banks. 3–4 days at a relaxed pace is ideal. Could easily spend a week.' },
    { q: 'What is the real price for a hot air balloon in Luxor?', a: 'Fair certified price: 1,500–2,000 EGP. Anything below 1,000 EGP is uncertified or has hidden add-ons. Fatal accidents have occurred.' },
    { q: 'Do you need a guide at Luxor temples?', a: 'Not mandatory but strongly recommended. Hire a government-licensed Egyptologist (official badge) for 800–1,200 EGP/day for genuine value.' },
    { q: 'Is it safe to cross to the West Bank?', a: 'Yes, completely safe. Use the local ferry (5 EGP) or taxi. The West Bank has Valley of Kings, Valley of Queens, and Medinet Habu.' },
    { q: 'What is the Luxor Pass and is it worth it?', a: '$100 USD Luxor Pass covers most major sites for 5 days. Worth it if visiting more than 5 sites including Valley of the Kings.' },
    { q: 'Which SIM card should I buy in Luxor?', a: 'Vodafone is recommended for Luxor — best coverage at temple sites including Valley of the Kings and Karnak. Buy at the official store on Luxor Temple Road (130 EGP for 15GB). Orange is also good (115 EGP). e& works in the city center but is weaker on the West Bank.' },
    { q: 'Can I visit Valley of the Kings independently?', a: 'Yes. Buy tickets at the official visitor center — not from any individual. Standard ticket includes 3 tombs. Tutankhamun requires a separate add-on (300 EGP). No photography inside most tombs — follow the rules strictly.' },
    { q: 'What is the best restaurant in Luxor?', a: 'Sofra Restaurant (East Bank) is a consistent local favorite — rooftop setting, authentic Egyptian home cooking, honest prices. Habiba\'s Kitchen (West Bank) is legendary for its simple, genuine local food.' },
    { q: 'How aggressive are the touts in Luxor?', a: 'Very aggressive near all temple entrances. The key phrase is "La shukran" (no thank you) said firmly while walking — do not make eye contact or engage. A licensed guide eliminates almost all harassment.' },
    { q: 'What trains go from Luxor to Cairo?', a: 'Several daily trains: 2nd class 200–350 EGP, takes 8–10 hours. Night train (sleeper) is worth doing. Book at the official Luxor train station ticket window only.' },
  ],
  aswan: [
    { q: 'What is Aswan best known for?', a: 'Abu Simbel temples, Philae Temple, Nubian culture, and the most scenic stretch of the Nile in Egypt. Egypt\'s southernmost major city.' },
    { q: 'How do I get from Luxor to Aswan?', a: 'Train is best: 2–3 hours, 60–150 EGP. Overnight sleeper train is a classic experience. Flying is 1 hour but much more expensive.' },
    { q: 'Is Abu Simbel worth the trip from Aswan?', a: 'Absolutely yes. Abu Simbel is one of the most impressive ancient monuments in the world. 3-hour drive — go on the early shared convoy bus.' },
    { q: 'What is a fair price for a felucca in Aswan?', a: '80–150 EGP per hour for the whole boat (not per person). Insist on this. 2-hour sunset ride should cost 160–300 EGP total.' },
    { q: 'Is Aswan safe for solo travelers?', a: 'Aswan is one of the safest cities in Egypt. Smaller, less hustling, and locals are known for genuine Nubian hospitality.' },
    { q: 'Which SIM card is best in Aswan?', a: 'Vodafone is recommended — best coverage in Aswan city, on feluccas, and importantly on the road to Abu Simbel. Buy at the Vodafone store on the Corniche (130 EGP for 15GB or 175 EGP for 25GB). WE is the cheapest but too slow for comfortable use. Important: there is NO signal at Abu Simbel itself — offline maps essential.' },
    { q: 'What is the Nubian culture in Aswan?', a: 'Nubian people have their own distinct culture, language (Nubian), and traditions. They are indigenous to the Nile Valley between Aswan and Sudan. Visiting Nubian villages is a cultural highlight — they are generally welcoming. Nubian villages are FREE to enter; any "entry fee" demand is a scam.' },
    { q: 'Is the Abu Simbel convoy mandatory?', a: 'Yes, for private vehicles. The official police convoy departs Aswan at 4am and returns around noon. Individual travel outside the convoy on this road is not permitted. Many tours also fly directly to Abu Simbel (much quicker but more expensive).' },
    { q: 'What is Philae Temple?', a: 'The beautiful temple of the goddess Isis on Agilkia Island, reachable by motorboat. Ticket: 180 EGP (boat included). The Sound & Light show in the evening (250 EGP) is spectacular and worth attending.' },
    { q: 'What should I bring for the Abu Simbel trip?', a: 'Minimum 1,000 EGP cash (NO ATMs there), 2L+ water per person, sun cream, hat, comfortable walking shoes, passport/photo ID, and your temple ticket (360 EGP) booked in advance.' },
  ],
};

export const CITY_LISTINGS = {
  'sharm-el-sheikh': {
    restaurants: [
      { name: 'Fares Fish Restaurant', desc: 'No-frills seafood spot beloved by locals and in-the-know tourists. Grilled fish by weight at honest prices. Order the sea bass.', area: 'Old Market', rating: 4.6, price: '€€', lat: 27.9058, lng: 34.3178, tags: ['seafood', 'local', 'no tourist tax'] },
      { name: 'El Masrien Restaurant', desc: 'Authentic Egyptian street food — falafel, koshary, ful medames. Extremely cheap. 95% Egyptian clientele. Order the koshary.', area: 'Hadaba', rating: 4.4, price: '€', lat: 27.9012, lng: 34.3201, tags: ['local', 'budget', 'breakfast'] },
      { name: 'Pomodoro', desc: 'Reliable Italian pizza and pasta. Fair pricing for the Naama Bay area. Popular with Russian and European visitors.', area: 'Naama Bay', rating: 4.2, price: '€€', lat: 27.9162, lng: 34.3289, tags: ['italian', 'pizza', 'family'] },
      { name: 'Hard Rock Cafe Sharm', desc: 'Consistent international quality. Good for homesick travelers. Prices are tourist-area level but fair for what you get.', area: 'Naama Bay', rating: 4.1, price: '€€€', lat: 27.9165, lng: 34.3292, tags: ['international', 'burgers', 'live music'] },
      { name: 'Tam Tam Oriental Restaurant', desc: 'Egyptian mezze and grills. Rooftop terrace with Naama Bay views. Better value than most Naama Bay competitors.', area: 'Naama Bay', rating: 4.3, price: '€€', lat: 27.9160, lng: 34.3285, tags: ['mezze', 'rooftop', 'egyptian'] },
      { name: 'Farsha Café', desc: 'Iconic terraced café carved into a cliff above the Red Sea. Best sunset view in Sharm. Order fresh juice and shisha. Not for a full meal.', area: 'Peace Road', rating: 4.7, price: '€€', lat: 27.9080, lng: 34.3250, tags: ['view', 'sunset', 'shisha', 'café'] },
      { name: 'Sakkala Restaurant', desc: 'Popular local Egyptian restaurant near Old Market. Full mezze spread, grilled meats. Consistent quality.', area: 'Sakkala', rating: 4.3, price: '€', lat: 27.9045, lng: 34.3190, tags: ['local', 'mezze', 'grills'] },
      { name: 'La Luna Restaurant', desc: 'Good quality Italian and international food. Family-friendly. Fair pricing for the strip.', area: 'Naama Bay', rating: 4.2, price: '€€', lat: 27.9158, lng: 34.3288, tags: ['italian', 'family', 'international'] },
    ],
    clinics: [
      { name: 'Sharm International Hospital', desc: 'Main hospital serving the area. Multilingual staff (Russian, English, Arabic). 24/7 emergency. Accepts travel insurance.', area: 'Peace Road', rating: 4.0, price: '€€€', lat: 27.9091, lng: 34.3251, tags: ['emergency', 'english', 'russian', '24h'] },
      { name: 'Hyperbaric Medical Center', desc: 'Specialist diving injury treatment. Decompression chamber on-site. Essential to know location before diving.', area: 'Naama Bay', rating: 4.8, price: '€€€', lat: 27.9155, lng: 34.3280, tags: ['diving', 'emergency', 'specialist'] },
      { name: 'Sharm Dental Center', desc: 'English-speaking dentist. Modern equipment. Fair pricing. Appointment recommended but walk-ins accepted.', area: 'Hadaba', rating: 4.5, price: '€€', lat: 27.9018, lng: 34.3188, tags: ['dental', 'english speaking', 'appointment'] },
      { name: 'Al Salam Pharmacy', desc: '24-hour pharmacy. Wide range of medications including prescription items. English-speaking staff.', area: 'Naama Bay', rating: 4.2, price: '€', lat: 27.9158, lng: 34.3283, tags: ['pharmacy', '24h', 'english'] },
      { name: 'Movenpick Medical Center', desc: 'Private clinic inside Movenpick resort. German and English speaking doctors. Faster service than public hospitals.', area: 'Naama Bay', rating: 4.5, price: '€€€', lat: 27.9170, lng: 34.3295, tags: ['private', 'german', 'english', 'fast'] },
    ],
    transport: [
      { name: 'Official White Taxi Stand', desc: 'Licensed taxis with regulated fares. Ask for the meter or agree price upfront. Standard short hop: 50–100 EGP.', area: 'Naama Bay', rating: 3.8, price: '€', lat: 27.9155, lng: 34.3282, tags: ['taxi', 'official', 'metered'] },
      { name: 'Careem / Uber App', desc: 'App-based ride-hailing with fixed fares. No negotiation. Download before arriving. Best and safest option.', area: 'Citywide', rating: 4.7, price: '€€', lat: 27.9158, lng: 34.3300, tags: ['app', 'fixed price', 'safe'] },
      { name: 'Hotel Resort Shuttle', desc: 'Many hotels offer free shuttles to Naama Bay. Check with your hotel before paying for taxis. Times vary per hotel.', area: 'Citywide', rating: 4.0, price: '€', lat: 27.9100, lng: 34.3250, tags: ['shuttle', 'free', 'hotel'] },
    ],
    activities: [
      { name: 'Camel Dive Club', desc: 'PADI 5-star dive center. One of the oldest and most respected in Sharm. Multilingual instructors. Clear pricing.', area: 'Naama Bay', rating: 4.8, price: '€€€', lat: 27.9171, lng: 34.3294, tags: ['diving', 'PADI', 'certified'] },
      { name: 'Sinai Divers', desc: 'German-managed PADI dive center. Excellent safety record. Strong reputation for beginners.', area: 'Naama Bay', rating: 4.7, price: '€€€', lat: 27.9169, lng: 34.3291, tags: ['diving', 'PADI', 'beginners'] },
      { name: 'Ras Mohammed National Park', desc: 'Best snorkeling in Sinai. Entry 200 EGP. Rent snorkel gear or join day boat trips. World-class coral reefs.', area: 'South Sinai', rating: 4.9, price: '€€', lat: 27.7329, lng: 34.2421, tags: ['snorkeling', 'nature', 'official'] },
      { name: 'Quad Runner Sharm', desc: 'Desert quad biking in the Sinai. PADI-vetted operator. Clear pricing: 700 EGP/hour per quad. No hidden extras.', area: 'Hadaba', rating: 4.4, price: '€€', lat: 27.9010, lng: 34.3190, tags: ['quad', 'desert', 'adventure'] },
      { name: 'Sharm Old Market (Aladdin)', desc: 'The main souvenir and spice market. Expect vendor pressure. Bargain confidently — first quoted price is always 3x fair value.', area: 'Old Market', rating: 4.0, price: '€', lat: 27.9055, lng: 34.3180, tags: ['shopping', 'souvenir', 'market'] },
      { name: 'Nabq Bay Nature Reserve', desc: 'Large mangrove forest north of Sharm. Guided nature walks. Fewer tourists than Ras Mohammed. 100 EGP entry.', area: 'North Sharm', rating: 4.5, price: '€', lat: 27.9900, lng: 34.3600, tags: ['nature', 'mangrove', 'peaceful'] },
    ],
  },
  hurghada: {
    restaurants: [
      { name: 'Felfela Restaurant', desc: 'Egyptian classics done right. Grilled meats, mezze, fresh juices. Locals eat here. Tourists should too. Very good koshary.', area: 'El Dahar', rating: 4.5, price: '€€', lat: 27.2574, lng: 33.8085, tags: ['local', 'egyptian', 'authentic'] },
      { name: 'Paprika Restaurant', desc: 'Well-run restaurant with international and Egyptian menu. Good for families. Fair transparent prices.', area: 'New Hurghada', rating: 4.3, price: '€€', lat: 27.2401, lng: 33.8211, tags: ['family', 'international', 'reliable'] },
      { name: 'Portofino Restaurant', desc: 'Best Italian in Hurghada. Marina location. Fresh pasta. Reasonable prices for the quality.', area: 'Marina', rating: 4.4, price: '€€€', lat: 27.2396, lng: 33.8317, tags: ['italian', 'marina', 'pasta'] },
      { name: 'El Gezira Restaurant', desc: 'Nile fish and Egyptian mezze. Outdoor seating with harbor views. Trusted by Egyptian families.', area: 'El Dahar', rating: 4.3, price: '€€', lat: 27.2565, lng: 33.8090, tags: ['seafood', 'local', 'outdoor'] },
      { name: 'Koshary El Tahrir', desc: 'The real Egyptian national dish done perfectly. 30–50 EGP for a full meal. Standing or minimal seating.', area: 'El Dahar', rating: 4.6, price: '€', lat: 27.2580, lng: 33.8078, tags: ['koshary', 'budget', 'local'] },
      { name: 'El Sheikh Restaurant', desc: 'Grilled fish and seafood by weight. Very popular with locals. Ask what\'s fresh that day. Honest pricing in El Dahar.', area: 'El Dahar', rating: 4.4, price: '€€', lat: 27.2570, lng: 33.8075, tags: ['seafood', 'fish', 'local', 'grilled'] },
      { name: 'Pirates Bar & Grill', desc: 'Marina-view bar and restaurant. Good burgers and international food. Popular happy hour. Relaxed atmosphere.', area: 'Marina', rating: 4.2, price: '€€', lat: 27.2398, lng: 33.8315, tags: ['marina', 'bar', 'international', 'burgers'] },
      { name: 'White Elephant Restaurant', desc: 'Famous for live music and international buffet. Popular with long-stay and all-inclusive overflow crowds. Fun atmosphere.', area: 'Sahl Hasheesh Road', rating: 4.1, price: '€€', lat: 27.2200, lng: 33.8250, tags: ['buffet', 'live music', 'international'] },
    ],
    clinics: [
      { name: 'Hurghada General Hospital', desc: 'Main public hospital. Long waits. Free for emergencies. Good for serious cases. Best equipped public facility.', area: 'El Dahar', rating: 3.5, price: '€', lat: 27.2610, lng: 33.8070, tags: ['emergency', 'public', '24h'] },
      { name: 'Dr. Ahmed Medical Center', desc: 'Private clinic with English and Russian-speaking doctors. Covers general medicine and minor emergencies.', area: 'Sahl Hasheesh Road', rating: 4.4, price: '€€', lat: 27.2512, lng: 33.8145, tags: ['private', 'multilingual', 'general'] },
      { name: 'Diving Hyperbaric Center Hurghada', desc: 'Specialist chamber for diving injuries. Know this address before you dive. Open 24h for emergencies.', area: 'New Hurghada', rating: 4.7, price: '€€€', lat: 27.2450, lng: 33.8180, tags: ['diving', 'emergency', 'hyperbaric'] },
      { name: 'Ramsees Pharmacy', desc: '24-hour pharmacy in El Dahar. Wide medication selection including European brands. Russian-speaking staff.', area: 'El Dahar', rating: 4.2, price: '€', lat: 27.2590, lng: 33.8080, tags: ['pharmacy', '24h', 'russian'] },
      { name: 'Marina Medical Center', desc: 'Well-equipped private clinic near the marina. English-speaking. Good for travel-related illness, minor injuries.', area: 'Marina', rating: 4.3, price: '€€', lat: 27.2395, lng: 33.8320, tags: ['private', 'english', 'marina'] },
    ],
    transport: [
      { name: 'Careem / Uber', desc: 'Available and reliable in Hurghada. Fixed prices. No bargaining. Strongly recommended over street taxis.', area: 'Citywide', rating: 4.6, price: '€€', lat: 27.2574, lng: 33.8129, tags: ['app', 'safe', 'fixed price'] },
      { name: 'Airport Official Taxi Desk', desc: 'Inside arrivals hall. Fixed price to major areas posted on board. Use ONLY this, not drivers outside.', area: 'Hurghada Airport', rating: 4.0, price: '€€', lat: 27.1769, lng: 33.8036, tags: ['official', 'airport', 'fixed price'] },
      { name: 'Coastal Microbus (Route 1)', desc: 'Shared minibus along the main coastal road. 5–10 EGP flat fare. Locals use it. Not for luggage or late night.', area: 'Main Road', rating: 3.7, price: '€', lat: 27.2400, lng: 33.8150, tags: ['cheap', 'local', 'microbus'] },
      { name: 'Pink App', desc: 'Egyptian ride-hailing app popular in Hurghada. Download before arrival. Fixed app prices, no negotiation. Good coverage across all Hurghada zones.', area: 'Citywide', rating: 4.4, price: '€€', lat: 27.2574, lng: 33.8129, tags: ['app', 'fixed price', 'local app'] },
    ],
    activities: [
      { name: 'Red Sea Diving Safari', desc: 'Premium liveaboard and day diving. PADI certified crew. Top safety record in Hurghada. Clear pricing.', area: 'Marina', rating: 4.9, price: '€€€', lat: 27.2396, lng: 33.8317, tags: ['diving', 'liveaboard', 'premium'] },
      { name: 'Makadi Bay Snorkeling Trip', desc: 'Certified boat to pristine reef. Life jackets provided. Fixed departure time. No hidden fees confirmed.', area: 'Makadi Bay', rating: 4.5, price: '€€', lat: 27.1201, lng: 33.9012, tags: ['snorkeling', 'reef', 'family'] },
      { name: 'Desert Fox Quad Safari', desc: 'Honest desert safari operator. Group price clearly posted. 4-hour quad + camel + Bedouin dinner: 750 EGP/group.', area: 'Desert Road', rating: 4.5, price: '€€', lat: 27.2500, lng: 33.7900, tags: ['desert', 'quad', 'honest pricing'] },
      { name: 'Giftun Island Day Trip', desc: 'Full day on Giftun Island with snorkeling. Departs marina 9am. Includes lunch and gear. Fair: 350 EGP.', area: 'Marina', rating: 4.7, price: '€€', lat: 27.2400, lng: 33.8310, tags: ['island', 'snorkeling', 'day trip'] },
      { name: 'Kite Beach Hurghada', desc: 'Top kitesurfing spot — consistent wind all year. Lessons 600–900 EGP/session. Equipment rental available. Safe learning beach.', area: 'Kite Beach', rating: 4.8, price: '€€€', lat: 27.1700, lng: 33.8700, tags: ['kitesurfing', 'water sports', 'lessons'] },
      { name: 'El Dahar Old Town Walk', desc: 'The original Hurghada fishing village. Authentic markets, affordable restaurants, real local life. No tour needed — just explore.', area: 'El Dahar', rating: 4.5, price: '€', lat: 27.2580, lng: 33.8080, tags: ['local', 'market', 'free', 'authentic'] },
    ],
  },
  luxor: {
    restaurants: [
      { name: 'Sofra Restaurant', desc: 'Rooftop Egyptian restaurant in a restored old house. Genuine home cooking. Popular with educated tourists and locals alike.', area: 'East Bank', rating: 4.7, price: '€€', lat: 25.6995, lng: 32.6450, tags: ['local', 'rooftop', 'authentic'] },
      { name: "Habiba's Kitchen", desc: 'West Bank legend. Mama Habiba cooks daily. Whatever is in the pot, order it. Always honest, always delicious.', area: 'West Bank', rating: 4.8, price: '€', lat: 25.7301, lng: 32.6041, tags: ['local', 'west bank', 'home cooking'] },
      { name: 'Al Moudira Restaurant', desc: 'Upscale Egyptian cuisine in a beautiful setting. Worth a splurge. Reserve ahead. Outdoor garden dining.', area: 'West Bank', rating: 4.6, price: '€€€', lat: 25.7280, lng: 32.6050, tags: ['upscale', 'garden', 'reservation'] },
      { name: 'Snack Time Café', desc: 'Popular budget café near the Corniche. Good for breakfast and light meals. Reliable WiFi. Used by backpackers.', area: 'East Bank Corniche', rating: 4.2, price: '€', lat: 25.6980, lng: 32.6390, tags: ['budget', 'wifi', 'backpacker'] },
      { name: 'El Gezira Restaurant', desc: 'Simple Egyptian food on the East Bank. Fuul, tamiya, and grilled chicken. Local prices, no tourist markup.', area: 'East Bank', rating: 4.3, price: '€', lat: 25.6960, lng: 32.6410, tags: ['local', 'cheap', 'no markup'] },
      { name: 'Nile Valley Restaurant', desc: 'East Bank Corniche dining with Nile view. Egyptian and international menu. Fair tourist prices. Dinner reservations advised.', area: 'East Bank Corniche', rating: 4.2, price: '€€', lat: 25.6975, lng: 32.6395, tags: ['nile view', 'dinner', 'corniche'] },
      { name: 'Sundown Café (West Bank)', desc: 'Small café popular with cyclists and West Bank visitors. Cold drinks, light snacks. Very cheap. Great place to rest mid-route.', area: 'West Bank', rating: 4.4, price: '€', lat: 25.7310, lng: 32.6050, tags: ['west bank', 'cheap', 'cyclists'] },
    ],
    clinics: [
      { name: 'Luxor International Hospital', desc: '24/7 emergency. Accepts travel insurance. English-speaking staff. Best equipped hospital in the area.', area: 'East Bank', rating: 4.1, price: '€€€', lat: 25.6912, lng: 32.6501, tags: ['emergency', '24h', 'insurance'] },
      { name: 'Luxor German Hospital', desc: 'Private clinic with German and European standards. English, German, Arabic. Recommended for Western travelers.', area: 'East Bank', rating: 4.5, price: '€€€', lat: 25.6920, lng: 32.6490, tags: ['private', 'german', 'european standards'] },
      { name: 'Al Noor Pharmacy (24h)', desc: '24-hour pharmacy near Luxor Temple. Good medication stock. Staff speak basic English.', area: 'East Bank', rating: 4.0, price: '€', lat: 25.6990, lng: 32.6400, tags: ['pharmacy', '24h'] },
      { name: 'Nile Valley Medical Center', desc: 'Private clinic. Faster service than the main hospital. General medicine and minor emergencies. Accepts insurance.', area: 'East Bank', rating: 4.3, price: '€€', lat: 25.6930, lng: 32.6480, tags: ['private', 'fast', 'general'] },
    ],
    transport: [
      { name: 'Local Ferry (East to West Bank)', desc: 'Government-operated passenger ferry. 5 EGP per person. Runs every 30 min, 6am–10pm. Best value in Egypt.', area: 'Corniche', rating: 4.5, price: '€', lat: 25.6981, lng: 32.6387, tags: ['ferry', 'official', 'cheap'] },
      { name: 'Luxor Licensed Taxi Association', desc: 'Licensed taxis with official registration. Negotiate in EGP before departure. City fare: 40–80 EGP.', area: 'Citywide', rating: 3.9, price: '€€', lat: 25.6872, lng: 32.6396, tags: ['taxi', 'negotiable', 'licensed'] },
      { name: 'West Bank Bicycle Rental', desc: 'Rent from guesthouses near the ferry landing. 80–120 EGP/day. Best way to see the West Bank at your own pace.', area: 'West Bank', rating: 4.6, price: '€', lat: 25.7295, lng: 32.6055, tags: ['bicycle', 'independent', 'west bank'] },
    ],
    activities: [
      { name: 'Hod Hod Soliman Balloon', desc: 'ECAA-certified hot air balloon. Safety inspected. Early morning flights over Valley of the Kings. Best operator.', area: 'West Bank', rating: 4.8, price: '€€€', lat: 25.7381, lng: 32.6079, tags: ['balloon', 'certified', 'sunrise'] },
      { name: 'Karnak Temple Complex', desc: 'Largest ancient religious complex ever built. 134 columns in the hypostyle hall. Allocate 2–3 hours minimum. 300 EGP entry.', area: 'East Bank', rating: 5.0, price: '€€', lat: 25.7188, lng: 32.6573, tags: ['temple', 'official', 'must-see'] },
      { name: 'Valley of the Kings', desc: 'Official guided tours of the royal necropolis. 62 tombs discovered. Standard ticket (360 EGP) covers 3 tombs.', area: 'West Bank', rating: 4.9, price: '€€', lat: 25.7456, lng: 32.6014, tags: ['tombs', 'guided', 'official'] },
      { name: 'Luxor Museum', desc: 'World-class collection of New Kingdom artifacts. Air-conditioned. Much less crowded than Karnak. 200 EGP entry.', area: 'East Bank', rating: 4.8, price: '€€', lat: 25.7020, lng: 32.6380, tags: ['museum', 'must-see', 'AC'] },
      { name: 'Medinet Habu Temple', desc: 'Massive mortuary temple of Ramesses III — better preserved colors than Karnak. Fewer tourists. 180 EGP entry.', area: 'West Bank', rating: 4.8, price: '€', lat: 25.7195, lng: 32.5996, tags: ['temple', 'west bank', 'uncrowded'] },
      { name: 'Dendera Temple (Day Trip)', desc: 'Stunning Hathor temple 60km north of Luxor. Famous ceiling zodiac and intact colors. Best preserved of all Egyptian temples. Half-day trip. Ticket: 240 EGP.', area: '60km north of Luxor', rating: 4.9, price: '€€', lat: 26.1418, lng: 32.6704, tags: ['temple', 'day trip', 'must-see', 'colors'] },
      { name: 'Abydos Temple (Day Trip)', desc: 'Temple of Seti I — 3,300-year-old reliefs of stunning clarity. The Abydos King List (an ancient list of pharaohs) is here. 130km from Luxor. Ticket: 240 EGP.', area: '130km from Luxor', rating: 4.8, price: '€€', lat: 26.1856, lng: 31.9196, tags: ['temple', 'day trip', 'seti i', 'reliefs'] },
      { name: 'Valley of the Queens', desc: 'Necropolis of royal wives and princes. 90 tombs. Nefertari tomb (extra 1,400 EGP) has the finest painted walls in all Egypt. Standard entry: 180 EGP.', area: 'West Bank', rating: 4.7, price: '€€', lat: 25.7260, lng: 32.5980, tags: ['tombs', 'nefertari', 'west bank'] },
      { name: 'Deir el-Medina (Workers Village)', desc: 'The ancient village of the tomb builders. Better-preserved tombs with vivid colors. Far fewer tourists than Valley of Kings. Entry: 200 EGP.', area: 'West Bank', rating: 4.7, price: '€', lat: 25.7290, lng: 32.6030, tags: ['tombs', 'uncrowded', 'workers village'] },
      { name: 'Ramesseum (Mortuary Temple of Ramesses II)', desc: 'Ozymandias himself — the fallen colossus that inspired Shelley\'s poem. Largely unrestored and atmospheric. Entry: 180 EGP. Rarely crowded.', area: 'West Bank', rating: 4.6, price: '€', lat: 25.7312, lng: 32.6059, tags: ['temple', 'ramesses', 'atmospheric', 'uncrowded'] },
      { name: 'Deir el-Bahari (Hatshepsut Temple)', desc: 'The striking terraced mortuary temple of Egypt\'s female pharaoh. Three levels cut into the limestone cliffs. Entry: 240 EGP.', area: 'West Bank', rating: 4.9, price: '€€', lat: 25.7381, lng: 32.6073, tags: ['temple', 'hatshepsut', 'must-see'] },
      { name: 'Luxor Temple (Night Visit)', desc: 'Stunning illuminated at night. Originally connected to Karnak by a 3km sphinx avenue. 200 EGP entry. Night visit is spectacular.', area: 'East Bank', rating: 4.9, price: '€€', lat: 25.6994, lng: 32.6390, tags: ['temple', 'night visit', 'corniche'] },
      { name: 'Tomb of Nefertari (Queen Nefertari)', desc: 'The most beautifully painted tomb in Egypt. Floor-to-ceiling intact color. Maximum 150 visitors per day. Book ahead. Extra 1,400 EGP ticket.', area: 'Valley of the Queens', rating: 5.0, price: '€€€', lat: 25.7265, lng: 32.5975, tags: ['tomb', 'nefertari', 'must-see', 'paintings'] },
      { name: 'Colossi of Memnon', desc: 'Two 18-meter statues of Amenhotep III. Free to visit — no ticket needed. They\'ve stood here for 3,400 years. Best at sunrise.', area: 'West Bank', rating: 4.6, price: '€', lat: 25.7217, lng: 32.6108, tags: ['free', 'sunrise', 'statues', 'west bank'] },
    ],
  },
  aswan: {
    restaurants: [
      { name: 'Nubian House Restaurant', desc: 'Authentic Nubian cuisine in a traditional house overlooking the Nile. Ful, tamiya, fish, and local stews.', area: 'Elephantine Island', rating: 4.6, price: '€€', lat: 24.0901, lng: 32.8931, tags: ['nubian', 'nile view', 'authentic'] },
      { name: 'Al Masri Restaurant', desc: 'Egyptian staples on the Corniche. Grilled chicken, rice, salads. Honest pricing. Popular with local families.', area: 'Corniche', rating: 4.4, price: '€', lat: 24.0881, lng: 32.9001, tags: ['local', 'family', 'cheap'] },
      { name: 'Panorama Restaurant', desc: 'Best view in Aswan — Nile panorama from the rooftop. Egyptian and grilled food. Fair prices for the setting.', area: 'Corniche', rating: 4.3, price: '€€', lat: 24.0885, lng: 32.9005, tags: ['nile view', 'rooftop', 'panoramic'] },
      { name: 'Aswan Moon Restaurant', desc: 'Floating restaurant on the Nile. Very popular with budget travelers. Egyptian dishes, fresh fish, good value.', area: 'Corniche', rating: 4.2, price: '€€', lat: 24.0875, lng: 32.8995, tags: ['floating', 'nile', 'fish'] },
      { name: 'Koshary Aswan', desc: 'Best koshary in Aswan. Huge portions, 30–40 EGP. Open from morning until midnight. Local institution.', area: 'City Center', rating: 4.5, price: '€', lat: 24.0880, lng: 32.8990, tags: ['koshary', 'budget', 'local'] },
      { name: 'El Trompiz Restaurant', desc: 'West Bank restaurant with Nile view. Popular with felucca day-trippers. Fresh fish and Nubian cooking. Honest prices.', area: 'West Bank', rating: 4.4, price: '€€', lat: 24.0870, lng: 32.8870, tags: ['west bank', 'fish', 'nile view'] },
      { name: 'Aswan Cultural Center Café', desc: 'Café attached to the Nubian Museum. Good coffee and light meals. Peaceful courtyard. Air-conditioned.', area: 'Nubian Museum', rating: 4.2, price: '€', lat: 24.0815, lng: 32.9150, tags: ['café', 'AC', 'museum', 'peaceful'] },
    ],
    clinics: [
      { name: 'Aswan University Hospital', desc: '24/7 emergency. Best-equipped hospital in southern Egypt. Ask for the international patient desk.', area: 'University District', rating: 3.9, price: '€€', lat: 24.0812, lng: 32.9145, tags: ['emergency', '24h', 'public'] },
      { name: 'Ibn Sina Private Hospital', desc: 'Best private hospital in Aswan. English-speaking staff. Accepts international insurance. Modern facilities.', area: 'Corniche', rating: 4.3, price: '€€€', lat: 24.0850, lng: 32.9020, tags: ['private', 'english', 'insurance'] },
      { name: 'Al Shifa Pharmacy (24h)', desc: '24-hour pharmacy near train station. Stocks common medications and European brands.', area: 'Train Station Area', rating: 4.1, price: '€', lat: 24.0870, lng: 32.9000, tags: ['pharmacy', '24h'] },
      { name: 'Corniche Medical Clinic', desc: 'Private clinic on the Corniche. Good for travel illness, mild infections, dehydration. English-speaking doctor on call.', area: 'Corniche', rating: 4.2, price: '€€', lat: 24.0885, lng: 32.9002, tags: ['private', 'corniche', 'general'] },
    ],
    transport: [
      { name: 'Nile Motor Boat (Corniche Taxi)', desc: 'Small motorboats ferrying between east bank, Elephantine Island, west bank. 5–10 EGP per trip.', area: 'Corniche', rating: 4.2, price: '€', lat: 24.0889, lng: 32.8998, tags: ['boat', 'nile', 'cheap'] },
      { name: 'Official Taxi Rank (Train Station)', desc: 'Outside the train station. Agree EGP price before departing. City center trips: 30–60 EGP.', area: 'Train Station', rating: 3.8, price: '€€', lat: 24.0869, lng: 32.8994, tags: ['taxi', 'official', 'train station'] },
      { name: 'Abu Simbel Official Convoy Bus', desc: 'Departs 4am from central Aswan. Safe, official, police-escorted. 400–600 EGP per person return. Book day before.', area: 'Aswan', rating: 4.6, price: '€€', lat: 24.0889, lng: 32.8998, tags: ['abu simbel', 'official', 'convoy'] },
    ],
    activities: [
      { name: 'Philae Temple (Official)', desc: 'Island temple of Isis. Official boat from the dock included in ticket. Spectacular sunset light.', area: 'Agilkia Island', rating: 4.9, price: '€€', lat: 24.0234, lng: 32.8842, tags: ['temple', 'island', 'official'] },
      { name: 'Abu Simbel Official Convoy', desc: 'Official shared bus convoy departs 4am from Aswan. Arrives Abu Simbel 7am. Best value way.', area: 'Aswan Depot', rating: 4.7, price: '€€', lat: 24.0889, lng: 32.8998, tags: ['abu simbel', 'convoy', 'official'] },
      { name: 'Nubian Village Felucca Trip', desc: 'Traditional sailing boat to Nubian village. Genuine cultural experience. Whole boat: 200–300 EGP return.', area: 'Nile', rating: 4.6, price: '€', lat: 24.0850, lng: 32.8900, tags: ['felucca', 'nubian', 'cultural'] },
      { name: 'Aswan Botanical Garden', desc: 'Peaceful island botanical garden on Kitchener\'s Island. Take motor boat to reach. Entry 50 EGP.', area: 'Kitchener Island', rating: 4.3, price: '€', lat: 24.0920, lng: 32.8880, tags: ['garden', 'peaceful', 'island'] },
      { name: 'Nubian Museum', desc: 'World-class museum of Nubian artifacts, history, and culture. 150 EGP entry. Air-conditioned. A must-see in Aswan.', area: 'Aswan City', rating: 4.8, price: '€', lat: 24.0815, lng: 32.9148, tags: ['museum', 'AC', 'must-see'] },
      { name: 'Philae Sound & Light Show', desc: 'Evening light show at Philae Temple. 250 EGP. Runs Wednesday, Thursday, Saturday (varies). Book in advance.', area: 'Philae Island', rating: 4.5, price: '€€', lat: 24.0234, lng: 32.8842, tags: ['evening', 'light show', 'philae'] },
      { name: 'Abu Simbel Temples', desc: 'Twin temples of Ramesses II and Nefertari carved from a single mountain. Relocated 1968 to save from flooding. The most spectacular ancient monuments in all Africa. Entry: 360 EGP. Convoy departs 4am.', area: '280km south of Aswan', rating: 5.0, price: '€€€', lat: 22.3372, lng: 31.6258, tags: ['must-see', 'ramesses', 'convoy', 'world heritage'] },
      { name: 'Temple of Kalabsha', desc: 'Massive Nubian temple relocated to Lake Nasser shore. Dedicated to god Mandolis. Reachable only by boat from the High Dam area. Entry: 120 EGP + boat.', area: 'Lake Nasser shore', rating: 4.5, price: '€€', lat: 23.9655, lng: 32.8729, tags: ['nubian', 'lake nasser', 'boat access'] },
      { name: 'Temple of Beit el-Wali', desc: 'Rock-cut temple of Ramesses II with rare colorful painted reliefs. Adjacent to Kalabsha. Often visited together. Entry included with Kalabsha ticket.', area: 'Lake Nasser shore', rating: 4.4, price: '€', lat: 23.9660, lng: 32.8722, tags: ['ramesses', 'painted reliefs', 'nubian'] },
      { name: 'Kom Ombo Temple', desc: 'Unique double temple dedicated to two gods simultaneously: Sobek (crocodile) and Horus. On the Nile, 65km north of Aswan. Nile cruise stop. Entry: 200 EGP.', area: '65km north of Aswan', rating: 4.8, price: '€€', lat: 24.4522, lng: 32.9286, tags: ['temple', 'crocodile', 'nile', 'day trip'] },
      { name: 'Edfu Temple (Horus)', desc: 'Best preserved ancient Egyptian temple. Dedicated to Horus. Built 237–57 BC. 30-meter tall pylon. 120km north of Aswan. Entry: 200 EGP.', area: '120km north of Aswan', rating: 4.9, price: '€€', lat: 24.9779, lng: 32.8730, tags: ['temple', 'horus', 'preserved', 'ptolemaic'] },
      { name: 'Elephantine Island Ruins', desc: 'Ancient settlement older than Aswan city itself. Temple of Khnum ruins, Nilometer, and small archaeological museum. Reachable by 5 EGP motor boat from Corniche.', area: 'Nile, central Aswan', rating: 4.4, price: '€', lat: 24.0892, lng: 32.8924, tags: ['island', 'ruins', 'nilometer', 'free boat'] },
      { name: 'Temple of Satet (Elephantine)', desc: 'Ancient temple fragments of Satet the goddess of the Nile flood on Elephantine Island. Small but historically significant as one of the oldest cult sites in Egypt.', area: 'Elephantine Island', rating: 4.1, price: '€', lat: 24.0890, lng: 32.8920, tags: ['ancient', 'goddess', 'elephantine', 'lesser-known'] },
      { name: 'Aswan High Dam (Al-Saad Al-Ali)', desc: 'One of the largest embankment dams in the world. Built 1960–1970. Created Lake Nasser (550km long). Soviet-Egyptian engineering landmark. Entry: 80 EGP.', area: 'South of Aswan', rating: 4.3, price: '€', lat: 23.9699, lng: 32.8779, tags: ['dam', 'modern history', 'soviet era', 'lake nasser'] },
      { name: 'Wadi el-Subua Temple', desc: 'Relocated Ramesses II temple with rare painted Christian-era alterations over the ancient hieroglyphs. Lake Nasser boat access only. Part of guided Lake Nasser cruises.', area: 'Lake Nasser', rating: 4.5, price: '€€€', lat: 22.7722, lng: 31.9867, tags: ['ramesses', 'lake nasser', 'cruise only', 'unique'] },
      { name: 'Qertassi Kiosk (near Kalabsha)', desc: 'Small open Roman-era kiosk temple. Often overlooked but has beautiful Hathor-headed columns. Adjacent to Kalabsha. No extra ticket needed.', area: 'Lake Nasser shore', rating: 4.2, price: '€', lat: 23.9658, lng: 32.8724, tags: ['roman', 'kiosk', 'lesser-known', 'free with kalabsha'] },
    ],
  },
};

export const CITY_TRANSPORT = {
  'sharm-el-sheikh': {
    intro: 'Getting around Sharm El Sheikh requires understanding the taxi system. There are no tourist buses. Uber and Careem are your safest, most transparent options.',
    tips: [
      { title: 'Uber / Careem — Use These First', desc: 'Both apps operate in Sharm. Fixed, transparent prices. No negotiation, no drama. Download both before landing.' },
      { title: 'White Official Taxis', desc: 'Licensed taxis are white. Always ask for the meter. If "broken," negotiate before moving. Standard short hop: 50–100 EGP.' },
      { title: 'Airport Transfer', desc: 'Pre-book through your hotel, or use the official taxi desk inside arrivals. Do NOT follow anyone who approaches you unsolicited.' },
      { title: 'Resort Shuttles', desc: 'Many hotels run free shuttles to Naama Bay. Check with your hotel before paying for a taxi.' },
      { title: 'Between Areas', desc: 'Naama Bay to Old Market: ~60 EGP. Naama Bay to Hadaba: ~50 EGP. Any trip over 200 EGP within city is being overcharged.' },
      { title: 'SIM Card for Navigation', desc: 'Vodafone or Orange SIM gives you Google Maps navigation throughout Sharm. 15GB for 115–130 EGP from official stores in Naama Bay Mall or Old Market.' },
    ],
    safety: 'Never get into an unmarked car. Always confirm price before moving. At night, use Careem/Uber for the tracking feature and share your location with someone you trust.',
  },
  hurghada: {
    intro: 'Hurghada is spread over 40km of coastline. Transport is essential and scams are rampant. The airport approach road has the highest concentration of scam taxis in Egypt.',
    tips: [
      { title: 'Careem & Pink App — Best Options', desc: 'Careem and Pink App are the most used and trusted ride apps in Hurghada. Fixed prices, no negotiation. Download both before arrival.' },
      { title: 'The Microbus (Local Secret)', desc: 'Shared minibuses run along the main coastal road for 5–10 EGP. Locals use them. Not for tourists with luggage but fine for short solo hops.' },
      { title: 'Hotel Transfer vs Street Taxi', desc: 'Hotel transfers are overpriced but safe. Street taxis outside the airport are the highest risk. Use only the official desk inside the terminal.' },
      { title: 'Between Resort Zones', desc: 'El Dahar to Marina: 60–80 EGP. Marina to Sahl Hasheesh: 100–150 EGP. Airport to any zone: 120–180 EGP.' },
      { title: 'Renting a Car', desc: 'Not recommended for first-timers. Egyptian traffic is chaotic. A driver-guide for the day (400–600 EGP) is smarter and safer.' },
      { title: 'SIM Card for Maps & Careem', desc: 'Orange or Vodafone SIM essential for Careem app and Google Maps. Buy at official store on Sahl Hasheesh Road or Marina. 15GB: 115–130 EGP.' },
    ],
    safety: 'The airport approach road has the highest concentration of scam taxis. Always walk to the official desk inside the terminal. Never accept a ride from anyone approaching you outside arrivals.',
  },
  luxor: {
    intro: 'Luxor is split between East Bank (hotels, temples, train station) and West Bank (tombs, Valley of Kings). Getting between them is easy and cheap. The local ferry is one of Egypt\'s great budget transport gems.',
    tips: [
      { title: 'The Local Ferry — 5 EGP', desc: 'Government passenger ferry across the Nile. Best value transport in all of Egypt. 5 EGP per person. Runs every 30 min, 6am–10pm.' },
      { title: 'Calèche (Horse Carriage)', desc: 'Traditional and scenic but requires firm negotiation. Agree on full round-trip price in EGP before starting. Standard: 100–200 EGP.' },
      { title: 'Taxi Rules in Luxor', desc: 'Negotiate in EGP only. Refuse USD quotes. City trips: 40–80 EGP. Airport: 80–120 EGP. Full day with driver: 400–600 EGP.' },
      { title: 'Bicycle on the West Bank', desc: 'The West Bank is flat and perfect for cycling. Rent for 80–120 EGP/day from guesthouses near the ferry landing.' },
      { title: 'Train to Cairo/Aswan', desc: 'Luxor is on the Cairo–Aswan rail line. To Aswan: 2–3 hours, 60–150 EGP. To Cairo: 8–10 hours overnight, 200–500 EGP.' },
      { title: 'SIM Card for Navigation', desc: 'Vodafone has best coverage near temple sites. Buy at Luxor Temple Road store. 15GB = 130 EGP. Crucial for offline maps and guide apps.' },
    ],
    safety: 'Avoid guides who approach you near ticket booths. Licensed tourist guides wear government-issued IDs. Night travel on the West Bank: use hotel-arranged or pre-agreed transport.',
  },
  aswan: {
    intro: 'Aswan is the smallest and most manageable city in this guide. The Nile is your main highway — boats replace taxis for many trips. The city is compact and much of it is walkable.',
    tips: [
      { title: 'Motor Boats (Nile Taxi)', desc: 'Short boat trips across the Nile: 5–15 EGP. Board from the Corniche. Agree on price for the trip, not per person.' },
      { title: 'Felucca for Leisure', desc: 'Traditional sailing for Nile cruising. For a sunset trip, 1.5 hours is enough. 150–200 EGP total for the whole boat.' },
      { title: 'Walk the Corniche', desc: 'Aswan\'s riverside promenade connects hotels, restaurants, and the ferry dock. Most central sights are walkable.' },
      { title: 'Train to Luxor/Cairo', desc: 'Train station is central. To Luxor: 2–3 hours, 60–80 EGP. Air-conditioned 1st and 2nd class available. Book at ticket window.' },
      { title: 'Abu Simbel — Official Convoy', desc: '4am official convoy is the only legal land route to Abu Simbel. Individual travel outside the convoy is not permitted for security reasons.' },
      { title: 'SIM Card for Maps', desc: 'Vodafone recommended — best coverage in Aswan and on the Abu Simbel road. 25GB (175 EGP) better for day trips. Buy on Corniche. No signal at Abu Simbel site itself.' },
    ],
    safety: 'Aswan is Egypt\'s most relaxed city for tourists. Scams are milder here than in Luxor or Cairo. Still negotiate all felucca and taxi prices before departure and never pay in advance.',
  },
};

export const CITY_ATM = {
  'sharm-el-sheikh': {
    intro: 'ATMs widely available in Naama Bay and near hotels. Egyptian Pound (EGP) is the only currency you should use for daily transactions.',
    tips: [
      'Use ATMs inside banks or hotels — avoid standalone ATMs in dark or isolated locations.',
      'Daily withdrawal limit: typically 5,000–10,000 EGP per card (3,000–5,000 EGP per transaction).',
      'Your home bank charges international fees of 2–4%. Factor this into your budget.',
      'Currency exchange is available everywhere but rates vary wildly — compare before exchanging.',
      'Do NOT exchange money with street touts — always illegal, often counterfeit notes.',
      'USD and EUR accepted at hotels but at unfavorable EGP conversion rates.',
      'Banque Misr ATMs inside hotel lobbies are the most tourist-friendly option.',
      'Most supermarkets (Carrefour, Spinneys) accept Visa and Mastercard. Markets and taxis are cash only.',
      'Vodafone or Orange SIM card (130 EGP) recommended for using banking apps in Egypt.',
    ],
    bestATMs: ['Banque Misr (Naama Bay)', 'CIB ATM (Naama Bay Mall)', 'HSBC (Peace Road)', 'NBE (Hadaba area)', 'Alex Bank (Old Market area)'],
    avoidList: ['Standalone ATMs with no bank branding', 'ATMs near crowded markets (skimming risk)', 'Airport exchange counters (worst rates)', 'Hotel lobby private currency desks'],
    rate: '1 USD ≈ 50 EGP (check xe.com for live rate before traveling)',
  },
  hurghada: {
    intro: 'Good ATM coverage in the Marina, Sahl Hasheesh, and El Dahar. The old town has fewer options. The airport has ATMs but with worse rates.',
    tips: [
      'Banque Misr and CIB are the most reliable and tourist-friendly ATMs.',
      'ATMs at the airport have high fees — emergency use only.',
      'All-inclusive resorts often add a card surcharge of 3–5%. Ask before using.',
      'Keep 500–1,000 EGP cash on you at all times for markets and tips.',
      'Count every note at the exchange desk before leaving — errors "happen" frequently.',
      'Official bank exchange rates are always better than street money changers.',
      'NBE (National Bank of Egypt) ATMs have the highest daily limits.',
      'El Dahar old town has fewer ATMs — withdraw before heading there.',
      'Marina area has the best ATM cluster — Banque Misr, CIB, and Alex Bank all nearby.',
    ],
    bestATMs: ['Banque Misr (Marina)', 'CIB (Sahl Hasheesh)', 'NBE ATM (El Dahar)', 'Alex Bank (New Hurghada)', 'QNB (Marina road)'],
    avoidList: ['Airport standalone kiosks', 'Exchange windows near tourist sites', 'Hotel lobby exchange desks (worst rates in Egypt)', 'Market area standalone ATMs'],
    rate: '1 EUR ≈ 54 EGP (check xe.com for live rate before traveling)',
  },
  luxor: {
    intro: 'Reliable ATMs on the East Bank near the Corniche. The West Bank has very limited ATM access — always withdraw before crossing.',
    tips: [
      'Withdraw cash before taking the ferry to the West Bank. No ATMs near the tombs.',
      'Banque Misr on the Corniche is the most reliable and well-stocked ATM.',
      'Most temples, tickets, and guides are cash only. Plan ahead.',
      'Tipping is expected everywhere — keep small bills (5, 10, 20 EGP) always.',
      'The Luxor Pass ($100 USD) is purchased in USD cash — have it ready at the museum.',
      'Hotel currency exchange desks are convenient but typically 5–8% worse than bank rates.',
      'ATMs often run out of cash during high season (November–January). Withdraw ahead.',
      'Full day on the West Bank: budget 800–1,500 EGP cash for tickets + guide + transport + food.',
      'Train to Cairo: buy ticket at the station window. Cash only. No card option at Luxor station.',
    ],
    bestATMs: ['Banque Misr (Corniche)', 'NBE (Luxor Temple Road)', 'CIB (East Bank)', 'Alex Bank (near Train Station)', 'QNB (City Center)'],
    avoidList: ['West Bank has no reliable ATMs — stock up before crossing', 'Any individual offering "better exchange rate" on the street', 'Hotel currency desks before checking bank rate first'],
    rate: '1 GBP ≈ 63 EGP (check xe.com for live rate before traveling)',
  },
  aswan: {
    intro: 'Limited but functional ATM access on the Corniche. Cash is essential here for feluccas, markets, and most local services.',
    tips: [
      'The Corniche has the best ATM cluster — use Banque Misr or NBE.',
      'Train station area also has ATMs if arriving by rail.',
      'Abu Simbel has NO ATMs. Bring all cash for the day before departure.',
      'Felucca captains, market vendors, and ferry operators are cash only.',
      'Nubian village restaurants rarely accept cards.',
      'Withdraw enough for your whole stay on arrival — Aswan ATMs can run low.',
      'Abu Simbel entry ticket (360 EGP) + Abu Simbel transport (400–600 EGP) = bring minimum 1,200 EGP cash for that day.',
      'Philae Temple entry (180 EGP) + Sound & Light show (250 EGP): have cash ready.',
      'Nubian Museum (150 EGP): cash only at the ticket window.',
    ],
    bestATMs: ['Banque Misr (Corniche)', 'NBE (Train Station area)', 'Egyptian Arab Land Bank (Corniche)', 'CIB (City Center)', 'Alex Bank (South Corniche)'],
    avoidList: ['No ATMs on Elephantine Island', 'No ATMs at Abu Simbel or Philae Temple', 'No ATMs in Nubian villages'],
    rate: '1 USD ≈ 50 EGP (check xe.com for live rate before traveling)',
  },
};

export const CITY_SAFETY = {
  'sharm-el-sheikh': {
    rating: 'Generally Safe',
    ratingLevel: 'medium-low',
    overview: 'Sharm El Sheikh is heavily secured by Egyptian authorities. Violent crime against tourists is extremely rare. The main risks are petty scams, overcharging, and minor theft in crowded areas.',
    tips: [
      { type: 'safe', text: 'Resort areas and Naama Bay are well-lit and well-patrolled 24 hours.' },
      { type: 'safe', text: 'Sinai Peninsula visa allows entry without a full Egypt visa for most nationalities.' },
      { type: 'safe', text: 'Tourist Police presence is strong at all major tourist areas and beaches.' },
      { type: 'safe', text: 'Thousands of European package tourists visit safely every week of the year.' },
      { type: 'caution', text: 'Be aware of your belongings on busy beach strips — petty theft does occur.' },
      { type: 'caution', text: 'Verify any excursion operator is officially licensed before paying.' },
      { type: 'caution', text: 'Unlicensed quad biking operators have caused injuries — choose certified companies only.' },
      { type: 'caution', text: 'Restaurant bill padding is common — always check every line item.' },
      { type: 'warning', text: 'Do not travel beyond resort areas into North Sinai without local advice on current conditions.' },
      { type: 'warning', text: 'Swimming: Respect all red flags. Red Sea currents and marine hazards can be deadly.' },
    ],
  },
  hurghada: {
    rating: 'Safe for Tourists',
    ratingLevel: 'low',
    overview: 'Hurghada is one of Egypt\'s most tourist-friendly cities. The main threat is financial scams, not personal safety. Standard big-city awareness applies, especially after dark.',
    tips: [
      { type: 'safe', text: 'Tourist areas are well-policed with cameras in major zones.' },
      { type: 'safe', text: 'All-inclusive resort zones are very secure environments with 24h security.' },
      { type: 'safe', text: 'The Marina and Sahl Hasheesh areas are particularly well-monitored.' },
      { type: 'safe', text: 'Hyperbaric center is available for diving emergencies — know the location before diving.' },
      { type: 'caution', text: 'El Dahar old town: exercise normal street awareness after midnight.' },
      { type: 'caution', text: 'Jet ski and watersports: insist on a signed safety briefing and life jacket.' },
      { type: 'caution', text: 'Solo women should use Careem/Uber at night, not street taxis.' },
      { type: 'caution', text: 'Hotel excursion desks: always compare prices with marina prices before booking.' },
      { type: 'warning', text: 'Always swim at designated beach areas with visible lifeguard presence.' },
      { type: 'warning', text: 'Driving at night outside the city on desert roads is risky — do not drive unfamiliar roads after dark.' },
    ],
  },
  luxor: {
    rating: 'Safe with Awareness',
    ratingLevel: 'medium',
    overview: 'Luxor is safe but has the highest concentration of aggressive touts and scammers of any city in this guide. Stay alert, be firm, and you will have a great trip. The history is worth it.',
    tips: [
      { type: 'safe', text: 'Tourist police are stationed at all major sites including Valley of Kings, Karnak, and Luxor Temple.' },
      { type: 'safe', text: 'Hotels and guesthouses are generally reliable and honest.' },
      { type: 'safe', text: 'The Corniche road is safe at all hours — well-lit and busy with tourists.' },
      { type: 'safe', text: 'Violent crime against tourists is extremely rare in Luxor.' },
      { type: 'caution', text: 'Approach to Karnak and Valley of Kings has persistent touts — a firm "La shukran" is your primary weapon.' },
      { type: 'caution', text: 'Unlicensed guides are everywhere. Only hire those with an official government ID badge.' },
      { type: 'caution', text: 'Be especially alert near the train station — commission touts target new arrivals.' },
      { type: 'caution', text: 'Alabaster shops and "factory tours" are the highest-pressure scam in Luxor.' },
      { type: 'warning', text: 'Night travel on the West Bank: use hotel-arranged transport or a pre-agreed driver.' },
      { type: 'warning', text: 'Hot air balloon rides: ONLY book ECAA-certified operators. Fatal accidents have occurred with uncertified companies.' },
    ],
  },
  aswan: {
    rating: 'Very Safe',
    ratingLevel: 'low',
    overview: 'Aswan is Egypt\'s most relaxed and safest tourist destination. Nubian people are genuinely welcoming. Scams exist but are milder and less aggressive than in Luxor or Cairo.',
    tips: [
      { type: 'safe', text: 'Aswan has very little petty crime compared to other Egyptian tourist cities.' },
      { type: 'safe', text: 'Felucca trips on the Nile are safe and a genuinely wonderful experience.' },
      { type: 'safe', text: 'The Corniche road is safe at all hours for walking.' },
      { type: 'safe', text: 'Nubian villages are generally safe and very welcoming to foreign visitors.' },
      { type: 'caution', text: 'Always negotiate felucca and boat prices before boarding — not after.' },
      { type: 'caution', text: 'Abu Simbel road: only travel on the official convoy, not privately.' },
      { type: 'caution', text: 'Nubian souvenir sellers can be persistent — firm politeness is sufficient.' },
      { type: 'caution', text: 'Felucca captain pricing: confirm "whole boat" vs "per person" explicitly.' },
      { type: 'warning', text: 'The desert around Aswan is extreme. Never hike without a guide and substantial water supply.' },
      { type: 'warning', text: 'Abu Simbel convoy: 4am departure — take security seriously and stay with the convoy.' },
    ],
  },
};