export const CITIES = [
  { id: 'sharm-el-sheikh', name: 'Sharm El Sheikh', nameRu: 'Шарм-эш-Шейх', nameDe: 'Scharm asch-Schaich', nameFr: 'Charm el-Cheikh', nameIt: 'Sharm el-Sheikh', nameEs: 'Sharm el-Sheij', nameZh: '沙姆沙伊赫', image: 'https://media.base44.com/images/public/69c689e2d4aa000453950c3f/720515fcf_generated_cfe87f7e.png', region: 'Red Sea' },
  { id: 'hurghada', name: 'Hurghada', nameRu: 'Хургада', nameDe: 'Hurghada', nameFr: 'Hurghada', nameIt: 'Hurghada', nameEs: 'Hurghada', nameZh: '赫尔格达', image: 'https://media.base44.com/images/public/69c689e2d4aa000453950c3f/790e4e258_generated_70147618.png', region: 'Red Sea' },
  { id: 'luxor', name: 'Luxor', nameRu: 'Луксор', nameDe: 'Luxor', nameFr: 'Louxor', nameIt: 'Luxor', nameEs: 'Luxor', nameZh: '卢克索', image: 'https://media.base44.com/images/public/69c689e2d4aa000453950c3f/810e2218d_generated_2acd98c5.png', region: 'Cultural' },
  { id: 'aswan', name: 'Aswan', nameRu: 'Асуан', nameDe: 'Assuan', nameFr: 'Assouan', nameIt: 'Assuan', nameEs: 'Asuán', nameZh: '阿斯旺', image: 'https://media.base44.com/images/public/69c689e2d4aa000453950c3f/7a020f162_generated_873418ba.png', region: 'Cultural' },
  { id: 'el-gouna', name: 'El Gouna', nameRu: 'Эль-Гуна', nameDe: 'El Gouna', nameFr: 'El Gouna', nameIt: 'El Gouna', nameEs: 'El Gouna', nameZh: '古纳', image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80', region: 'Red Sea' },
];

export const SERVICE_CATEGORIES = [
  { id: 'restaurant', label: 'Restaurants', labelRu: 'Рестораны', labelDe: 'Restaurants', labelFr: 'Restaurants', labelIt: 'Ristoranti', labelEs: 'Restaurantes', labelZh: '餐厅', icon: 'UtensilsCrossed' },
  { id: 'medical', label: 'Medical', labelRu: 'Медицина', labelDe: 'Medizin', labelFr: 'Médical', labelIt: 'Medico', labelEs: 'Médico', labelZh: '医疗', icon: 'Heart' },
  { id: 'transport', label: 'Transport', labelRu: 'Транспорт', labelDe: 'Transport', labelFr: 'Transport', labelIt: 'Trasporti', labelEs: 'Transporte', labelZh: '交通', icon: 'Car' },
  { id: 'activities', label: 'Activities', labelRu: 'Активности', labelDe: 'Aktivitäten', labelFr: 'Activités', labelIt: 'Attività', labelEs: 'Actividades', labelZh: '活动', icon: 'Waves' },
  { id: 'kids_family', label: 'Kids & Family', labelRu: 'Дети и семья', labelDe: 'Kinder & Familie', labelFr: 'Enfants & Famille', labelIt: 'Bambini & Famiglia', labelEs: 'Niños & Familia', labelZh: '亲子', icon: 'Baby' },
  { id: 'sim_internet', label: 'SIM & Internet', labelRu: 'SIM и интернет', labelDe: 'SIM & Internet', labelFr: 'SIM & Internet', labelIt: 'SIM & Internet', labelEs: 'SIM & Internet', labelZh: 'SIM卡', icon: 'Wifi' },
  { id: 'nightlife', label: 'Nightlife', labelRu: 'Ночная жизнь', labelDe: 'Nachtleben', labelFr: 'Vie nocturne', labelIt: 'Vita notturna', labelEs: 'Vida nocturna', labelZh: '夜生活', icon: 'Music' },
  { id: 'remote_work', label: 'Remote Work', labelRu: 'Удалённая работа', labelDe: 'Remote-Arbeit', labelFr: 'Télétravail', labelIt: 'Lavoro remoto', labelEs: 'Trabajo remoto', labelZh: '远程工作', icon: 'Laptop' },
];

export const SCAM_CATEGORIES = [
  { id: 'taxi', label: 'Taxi', icon: 'Car' },
  { id: 'shopping', label: 'Shopping', icon: 'ShoppingBag' },
  { id: 'tour', label: 'Tour', icon: 'Map' },
  { id: 'restaurant', label: 'Restaurant', icon: 'UtensilsCrossed' },
  { id: 'hotel', label: 'Hotel', icon: 'Building' },
  { id: 'money_exchange', label: 'Money Exchange', icon: 'Banknote' },
  { id: 'street_vendor', label: 'Street Vendor', icon: 'Store' },
  { id: 'other', label: 'Other', icon: 'AlertTriangle' },
];

export const LANGUAGES = [
  { code: 'en', label: 'EN', full: 'English' },
  { code: 'ru', label: 'RU', full: 'Русский' },
  { code: 'de', label: 'DE', full: 'Deutsch' },
  { code: 'fr', label: 'FR', full: 'Français' },
  { code: 'it', label: 'IT', full: 'Italiano' },
  { code: 'es', label: 'ES', full: 'Español' },
  { code: 'zh', label: '中文', full: '中文' },
  { code: 'ar', label: 'AR', full: 'العربية' },
];

export const TRANSLATIONS = {
  en: {
    hero_title: 'Navigate Egypt.',
    hero_subtitle: 'Like a Local.',
    hero_desc: 'Real prices. Scam alerts. Verified services. Your survival guide for Egypt.',
    search_placeholder: 'What is the fair price for a taxi in Luxor?',
    explore_cities: 'Explore Cities',
    price_checker: 'Price Checker',
    scam_map: 'Price Alerts Map',
    services: 'Services',
    emergency: 'Emergency',
    deals: 'Deals',
    reviews: 'Reviews',
    verified: 'Verified',
    report_scam: 'Report Unusual Price',
    fair_price: 'Fair Price',
    local_price: 'Local Price',
    tourist_price: 'Tourist Price',
    scam_price: 'High Price Alert',
    before_you_land: 'Before You Land',
    cost_calculator: 'Cost Calculator',
    phrases: 'Arabic Phrases',
    women_safety: 'Women Safety',
    tips: 'Tips & Guides',
    sos: 'SOS',
    all_cities: 'All Cities',
    book_now: 'Book Now',
    contact_whatsapp: 'Contact via WhatsApp',
    terms: 'Terms & Conditions',
    copyright: '© 2026 Locali Egypt – All rights reserved',
    scam_alerts: 'Price Alerts',
    real_prices: 'Real Prices',
    ask_local: 'Ask a Local',
    check_prices: 'Check Real Prices',
    pricing_insights: 'Pricing Intelligence',
    verified_services: 'Verified Services',
    select_city: 'Select your city',
    live: 'Live',
    safe_to_visit: 'Safe to visit',
    some_caution: 'Some caution',
    check_alerts: 'Check alerts',
    share: 'Share',
    submit: 'Submit',
    cancel: 'Cancel',
    loading: 'Loading…',
    no_data: 'No data yet',
    updated_today: 'Updated today',
    community_reports: 'community reports',
  },
  ru: {
    hero_title: 'Путешествуй по Египту.',
    hero_subtitle: 'Как местный.',
    hero_desc: 'Реальные цены. Оповещения о мошенничестве. Проверенные сервисы.',
    search_placeholder: 'Какая справедливая цена такси в Луксоре?',
    explore_cities: 'Города',
    price_checker: 'Проверка цен',
    scam_map: 'Карта предупреждений',
    services: 'Сервисы',
    emergency: 'Экстренная помощь',
    deals: 'Скидки',
    reviews: 'Отзывы',
    verified: 'Проверено',
    report_scam: 'Сообщить о необычной цене',
    fair_price: 'Справедливая цена',
    local_price: 'Местная цена',
    tourist_price: 'Цена для туриста',
    scam_price: 'Завышенная цена',
    before_you_land: 'Перед прилётом',
    cost_calculator: 'Калькулятор',
    phrases: 'Арабские фразы',
    women_safety: 'Безопасность женщин',
    tips: 'Советы',
    sos: 'SOS',
    all_cities: 'Все города',
    book_now: 'Забронировать',
    contact_whatsapp: 'WhatsApp',
    terms: 'Условия использования',
    copyright: '© 2026 Locali Egypt – Все права защищены',
    scam_alerts: 'Предупреждения о ценах',
    real_prices: 'Реальные цены',
    ask_local: 'Спросить местного',
    check_prices: 'Проверить цены',
    pricing_insights: 'Аналитика цен',
    verified_services: 'Проверенные сервисы',
    select_city: 'Выберите город',
    live: 'В эфире',
    safe_to_visit: 'Безопасно',
    some_caution: 'Будьте внимательны',
    check_alerts: 'Проверьте предупреждения',
    share: 'Поделиться',
    submit: 'Отправить',
    cancel: 'Отмена',
    loading: 'Загрузка…',
    no_data: 'Данных пока нет',
    updated_today: 'Обновлено сегодня',
    community_reports: 'отчёты сообщества',
  },
  fr: {
    hero_title: 'Naviguez en Égypte.',
    hero_subtitle: 'Comme un local.',
    hero_desc: 'Prix réels. Alertes prix. Services vérifiés. Votre guide de survie.',
    search_placeholder: "Quel est le prix juste d'un taxi à Louxor?",
    explore_cities: 'Explorer les villes',
    price_checker: 'Vérificateur de prix',
    scam_map: 'Carte des alertes prix',
    services: 'Services',
    emergency: 'Urgences',
    deals: 'Offres',
    reviews: 'Avis',
    verified: 'Vérifié',
    report_scam: 'Signaler un prix inhabituel',
    fair_price: 'Prix juste',
    local_price: 'Prix local',
    tourist_price: 'Prix touriste',
    scam_price: 'Prix élevé',
    before_you_land: "Avant d'atterrir",
    cost_calculator: 'Calculateur de coût',
    phrases: 'Phrases arabes',
    women_safety: 'Sécurité femmes',
    tips: 'Conseils & Guides',
    sos: 'SOS',
    all_cities: 'Toutes les villes',
    book_now: 'Réserver maintenant',
    contact_whatsapp: 'Contact WhatsApp',
    terms: 'Conditions générales',
    copyright: '© 2026 Locali Egypt – Tous droits réservés',
    scam_alerts: 'Alertes prix',
    real_prices: 'Prix réels',
    ask_local: 'Demander à un local',
    check_prices: 'Vérifier les prix',
    pricing_insights: 'Transparence des prix',
    verified_services: 'Services vérifiés',
    select_city: 'Sélectionnez votre ville',
    live: 'En direct',
    safe_to_visit: 'Sûr à visiter',
    some_caution: 'Prudence conseillée',
    check_alerts: 'Vérifier les alertes',
    share: 'Partager',
    submit: 'Envoyer',
    cancel: 'Annuler',
    loading: 'Chargement…',
    no_data: 'Aucune donnée',
    updated_today: 'Mis à jour aujourd’hui',
    community_reports: 'rapports communautaires',
  },
  de: {
    hero_title: 'Erkunde Ägypten.',
    hero_subtitle: 'Wie ein Einheimischer.',
    hero_desc: 'Echte Preise. Preis-Warnungen. Verifizierte Dienste.',
    search_placeholder: 'Was ist ein fairer Taxipreis in Luxor?',
    explore_cities: 'Städte',
    price_checker: 'Preis-Check',
    scam_map: 'Preis-Warnkarte',
    services: 'Dienste',
    emergency: 'Notfall',
    deals: 'Angebote',
    reviews: 'Bewertungen',
    verified: 'Verifiziert',
    report_scam: 'Ungewöhnlichen Preis melden',
    fair_price: 'Fairer Preis',
    local_price: 'Einheimischer Preis',
    tourist_price: 'Touristenpreis',
    scam_price: 'Hoher Preis',
    before_you_land: 'Vor der Landung',
    cost_calculator: 'Kostenrechner',
    phrases: 'Arabische Phrasen',
    women_safety: 'Frauen-Sicherheit',
    tips: 'Tipps & Guides',
    sos: 'SOS',
    all_cities: 'Alle Städte',
    book_now: 'Jetzt buchen',
    contact_whatsapp: 'WhatsApp Kontakt',
    terms: 'Nutzungsbedingungen',
    copyright: '© 2026 Locali Egypt – Alle Rechte vorbehalten',
    scam_alerts: 'Preis-Warnungen',
    real_prices: 'Echte Preise',
    ask_local: 'Einen Einwohner fragen',
    check_prices: 'Preise prüfen',
    pricing_insights: 'Preis-Transparenz',
    verified_services: 'Verifizierte Dienste',
    select_city: 'Stadt wählen',
    live: 'Live',
    safe_to_visit: 'Sicher zu besuchen',
    some_caution: 'Vorsicht empfohlen',
    check_alerts: 'Warnungen prüfen',
    share: 'Teilen',
    submit: 'Senden',
    cancel: 'Abbrechen',
    loading: 'Laden…',
    no_data: 'Keine Daten',
    updated_today: 'Heute aktualisiert',
    community_reports: 'Community-Berichte',
  },
  it: {
    hero_title: 'Esplora l\'Egitto.',
    hero_subtitle: 'Come un locale.',
    hero_desc: 'Prezzi reali. Avvisi truffe. Servizi verificati. La tua guida per l\'Egitto.',
    search_placeholder: 'Qual è il prezzo equo per un taxi a Luxor?',
    explore_cities: 'Esplora le città',
    price_checker: 'Verifica prezzi',
    scam_map: 'Mappa truffe',
    services: 'Servizi',
    emergency: 'Emergenza',
    deals: 'Offerte',
    reviews: 'Recensioni',
    verified: 'Verificato',
    report_scam: 'Segnala truffa',
    fair_price: 'Prezzo equo',
    local_price: 'Prezzo locale',
    tourist_price: 'Prezzo turista',
    scam_price: 'Prezzo truffa',
    before_you_land: 'Prima di atterrare',
    cost_calculator: 'Calcolatore costi',
    phrases: 'Frasi arabe',
    women_safety: 'Sicurezza donne',
    tips: 'Consigli & Guide',
    sos: 'SOS',
    all_cities: 'Tutte le città',
    book_now: 'Prenota ora',
    contact_whatsapp: 'Contatta WhatsApp',
    terms: 'Termini e condizioni',
    copyright: '© 2026 Locali Egypt – Tutti i diritti riservati',
    scam_alerts: 'Avvisi truffe',
    real_prices: 'Prezzi reali',
    ask_local: 'Chiedi a un locale',
  },
  es: {
    hero_title: 'Navega Egipto.',
    hero_subtitle: 'Como un local.',
    hero_desc: 'Precios reales. Alertas de precios. Servicios verificados. Tu guía de supervivencia.',
    search_placeholder: '¿Cuál es el precio justo de un taxi en Luxor?',
    explore_cities: 'Explorar ciudades',
    price_checker: 'Verificar precios',
    scam_map: 'Mapa de alertas de precios',
    services: 'Servicios',
    emergency: 'Emergencia',
    deals: 'Ofertas',
    reviews: 'Reseñas',
    verified: 'Verificado',
    report_scam: 'Reportar precio inusual',
    fair_price: 'Precio justo',
    local_price: 'Precio local',
    tourist_price: 'Precio turista',
    scam_price: 'Precio elevado',
    before_you_land: 'Antes de aterrizar',
    cost_calculator: 'Calculadora de costos',
    phrases: 'Frases en árabe',
    women_safety: 'Seguridad mujeres',
    tips: 'Consejos & Guías',
    sos: 'SOS',
    all_cities: 'Todas las ciudades',
    book_now: 'Reservar ahora',
    contact_whatsapp: 'Contactar WhatsApp',
    terms: 'Términos y condiciones',
    copyright: '© 2026 Locali Egypt – Todos los derechos reservados',
    scam_alerts: 'Alertas de precios',
    real_prices: 'Precios reales',
    ask_local: 'Pregunta a un local',
    check_prices: 'Ver precios reales',
    pricing_insights: 'Transparencia de precios',
    verified_services: 'Servicios verificados',
    select_city: 'Selecciona tu ciudad',
    live: 'En vivo',
    safe_to_visit: 'Seguro para visitar',
    some_caution: 'Precaución recomendada',
    check_alerts: 'Ver alertas',
    share: 'Compartir',
    submit: 'Enviar',
    cancel: 'Cancelar',
    loading: 'Cargando…',
    no_data: 'Sin datos',
    updated_today: 'Actualizado hoy',
    community_reports: 'reportes de la comunidad',
  },
  zh: {
    hero_title: '探索埃及。',
    hero_subtitle: '像当地人一样。',
    hero_desc: '真实价格。防骗提示。可信服务。您的埃及生存指南。',
    search_placeholder: '卢克索打车的合理价格是多少？',
    explore_cities: '探索城市',
    price_checker: '价格查询',
    scam_map: '价格异常地图',
    services: '服务',
    emergency: '紧急情况',
    deals: '优惠',
    reviews: '评价',
    verified: '已验证',
    report_scam: '举报价格异常',
    fair_price: '合理价格',
    local_price: '本地价格',
    tourist_price: '游客价格',
    scam_price: '异常价格',
    before_you_land: '出发前准备',
    cost_calculator: '费用计算器',
    phrases: '阿拉伯语短语',
    women_safety: '女性安全',
    tips: '旅游贴士',
    sos: 'SOS紧急',
    all_cities: '所有城市',
    book_now: '立即预订',
    contact_whatsapp: 'WhatsApp联系',
    terms: '服务条款',
    copyright: '© 2026 Locali Egypt – 版权所有',
    scam_alerts: '价格预警',
    real_prices: '真实价格',
    ask_local: '询问当地人',
    check_prices: '查看价格',
    pricing_insights: '价格透明度',
    verified_services: '认证服务',
    select_city: '选择城市',
    live: '实时',
    safe_to_visit: '适合出行',
    some_caution: '注意事项',
    check_alerts: '查看预警',
    share: '分享',
    submit: '提交',
    cancel: '取消',
    loading: '加载中…',
    no_data: '暂无数据',
    updated_today: '今日更新',
    community_reports: '社区报告',
  },
  ar: {
    hero_title: 'استكشف مصر.',
    hero_subtitle: 'كالسكان المحليين.',
    hero_desc: 'أسعار حقيقية. تنبيهات الأسعار. خدمات موثّقة. دليلك للتنقل في مصر.',
    search_placeholder: 'ما هو السعر العادل لسيارة أجرة في الأقصر؟',
    explore_cities: 'استكشاف المدن',
    price_checker: 'مدقق الأسعار',
    scam_map: 'خريطة الأسعار',
    services: 'الخدمات',
    emergency: 'الطوارئ',
    deals: 'العروض',
    reviews: 'التقييمات',
    verified: 'موثّق',
    report_scam: 'الإبلاغ عن سعر غير عادي',
    fair_price: 'السعر العادل',
    local_price: 'السعر المحلي',
    tourist_price: 'سعر السائح',
    scam_price: 'السعر المرتفع',
    before_you_land: 'قبل الوصول',
    cost_calculator: 'حاسبة التكاليف',
    phrases: 'العبارات العربية',
    women_safety: 'أمان المرأة',
    tips: 'نصائح وإرشادات',
    sos: 'طوارئ',
    all_cities: 'جميع المدن',
    book_now: 'احجز الآن',
    contact_whatsapp: 'تواصل عبر واتساب',
    terms: 'الشروط والأحكام',
    copyright: '© 2026 Locali Egypt – جميع الحقوق محفوظة',
    scam_alerts: 'تنبيهات الأسعار',
    real_prices: 'الأسعار الحقيقية',
    ask_local: 'اسأل أحد السكان',
    check_prices: 'تحقق من الأسعار',
    pricing_insights: 'شفافية الأسعار',
    verified_services: 'خدمات موثّقة',
    select_city: 'اختر مدينة',
    live: 'مباشر',
    safe_to_visit: 'آمن للزيارة',
    some_caution: 'بعض التنبيهات',
    check_alerts: 'راجع التنبيهات',
    share: 'مشاركة',
    submit: 'إرسال',
    cancel: 'إلغاء',
    loading: 'جارٍ التحميل…',
    no_data: 'لا توجد بيانات',
    updated_today: 'محدّث اليوم',
    community_reports: 'تقارير المجتمع',
  },
};


export function t(key, lang = 'en') {
  return TRANSLATIONS[lang]?.[key] || TRANSLATIONS.en[key] || key;
}

export function getCityName(city, lang = 'en') {
  const c = CITIES.find(c => c.id === city.id || c.id === city);
  if (!c) return city?.name || city;
  if (lang === 'ru') return c.nameRu;
  if (lang === 'de') return c.nameDe;
  if (lang === 'fr') return c.nameFr || c.name;
  if (lang === 'it') return c.nameIt || c.name;
  if (lang === 'es') return c.nameEs || c.name;
  if (lang === 'zh') return c.nameZh || c.name;
  return c.name;
}

export function generateTrackingCode(cityId, category) {
  const prefix = (cityId || 'eg').toUpperCase().slice(0, 3);
  const cat = (category || 'svc').toUpperCase().slice(0, 3);
  const rand = Math.random().toString(36).substring(2, 7).toUpperCase();
  return `LOC-${prefix}-${cat}-${rand}`;
}