// El Gouna — Complete City Content
// All prices in EGP. USD approximate at 1 USD ≈ 53 EGP (April 2026)

export const EL_GOUNA_META = {
  name: 'El Gouna',
  region: 'Red Sea',
  lat: 27.3973,
  lng: 33.6775,
  tagline: 'The Venice of the Red Sea — a private island city done right',
  intro: 'El Gouna is one of Egypt\'s most unique destinations: a self-contained resort city built across 13 islands connected by bridges and lagoons. Designed by Samih Sawiris, it has its own airport, marina, hospital, and over 20 hotels. Far more upscale than Hurghada. Kite Beach is world-famous. Prices are significantly higher than the rest of Egypt — here\'s the real breakdown.',
};

export const EL_GOUNA_LISTINGS = {
  restaurants: [
    {
      name: 'Kite Bar El Gouna',
      type: 'Beach Bar & Restaurant',
      desc: 'Legendary open-air bar and restaurant at Kite Beach. Front-row seat to world-class kitesurfing. Fresh grills, cold beer, and sunsets that justify the prices. Very popular with the kite crowd.',
      area: 'Kite Beach',
      hours: '10:00–23:00 daily',
      price_range: '150–350 EGP per person',
      price_usd: '$3–7',
      phone: '+20 65 358 0000',
      website: 'elgouna.com',
      rating: 4.7,
      verified: true,
      features: ['Beach view', 'English-friendly', 'Kitesurfing crowd', 'Cold drinks'],
      highlights: ['Best sunset spot in El Gouna', 'On the kite launch strip', 'Excellent cocktails'],
      accessibility: 'Beachfront — sandy paths, step-free to bar area',
      faq: [
        { q: 'Do I need a reservation?', a: 'Not usually — but book ahead for sunset on weekends (Oct–Apr).' },
        { q: 'Is it family-friendly?', a: 'Yes, but busier and noisier evenings. Families better at lunch.' },
      ],
      languages: ['en', 'de', 'ru'],
    },
    {
      name: 'Moodi\'s Restaurant',
      type: 'Egyptian Fine Dining',
      desc: 'One of El Gouna\'s most respected restaurants. Consistent Egyptian and Mediterranean cuisine. Rooftop terrace over the marina. Beloved by long-term El Gouna residents — a genuine local favorite.',
      area: 'El Gouna Downtown',
      hours: '12:00–23:00, closed Mondays',
      price_range: '200–450 EGP per person',
      price_usd: '$4–9',
      phone: '+20 65 358 0100',
      website: '',
      rating: 4.8,
      verified: true,
      features: ['Rooftop terrace', 'Egyptian cuisine', 'English menu', 'Reservation recommended'],
      highlights: ['Best Egyptian food in El Gouna', 'Rooftop marina view', 'Local institution'],
      accessibility: 'Rooftop access via stairs — no lift. Outdoor terrace.',
      faq: [
        { q: 'Is it expensive?', a: 'Mid-to-high range by El Gouna standards — still very affordable by European standards.' },
      ],
      languages: ['en', 'de'],
    },
    {
      name: 'The Captain\'s Inn',
      type: 'Seafood & Grills',
      desc: 'Marina-side seafood restaurant with wooden deck overlooking the boats. Great fresh catch of the day. Very popular with yacht owners and European long-stays. Book the deck table for sunset.',
      area: 'Abu Tig Marina',
      hours: '11:00–00:00 daily',
      price_range: '250–600 EGP per person',
      price_usd: '$5–12',
      phone: '+20 65 358 0200',
      website: '',
      rating: 4.6,
      verified: true,
      features: ['Marina view', 'Fresh seafood', 'Outdoor deck', 'Accepts cards'],
      highlights: ['Fresh catch daily', 'Boat-side dining', 'Sunset cocktails'],
      accessibility: 'Marina-level deck — step-free from marina path.',
      faq: [
        { q: 'Can I pay by card?', a: 'Yes. Visa and Mastercard accepted.' },
      ],
      languages: ['en', 'de', 'it'],
    },
    {
      name: 'Bleu Blanc (Club Med)',
      type: 'International Buffet',
      desc: 'The main restaurant inside Club Med El Gouna. Open to non-guests for dinner on reservation. Wide international buffet. Air-conditioned. Family-friendly with a kids\' section.',
      area: 'Club Med Resort',
      hours: '07:00–10:30, 12:30–14:30, 19:00–22:00',
      price_range: '550–750 EGP per person (buffet)',
      price_usd: '$11–15',
      phone: '+20 65 354 9100',
      website: 'clubmed.com',
      rating: 4.3,
      verified: true,
      features: ['Family-friendly', 'Kids section', 'AC', 'International cuisine', 'Buffet'],
      highlights: ['Widest buffet selection in El Gouna', 'Great for families', 'Included for Club Med guests'],
      accessibility: 'Fully accessible — ramps, elevators, AC throughout.',
      faq: [
        { q: 'Can non-guests dine here?', a: 'Yes, dinner is open to outside guests by reservation. Lunch is mainly for guests.' },
      ],
      languages: ['en', 'fr', 'de', 'it'],
    },
    {
      name: 'La Tortuga',
      type: 'Italian & Pizza',
      desc: 'Beloved Italian restaurant in El Gouna Downtown. Wood-fired pizza, fresh pasta, excellent tiramisu. Run by an Italian family for over 15 years. Best pizza in the Red Sea. Tiny — book in advance.',
      area: 'El Gouna Downtown',
      hours: '18:00–23:30, closed Wednesdays',
      price_range: '180–380 EGP per person',
      price_usd: '$3.5–8',
      phone: '+20 65 358 0300',
      website: '',
      rating: 4.9,
      verified: true,
      features: ['Italian owned', 'Wood-fired pizza', 'Intimate setting', 'Reservation required'],
      highlights: ['Best pizza on the Red Sea', '15+ year institution', 'Authentic tiramisu'],
      accessibility: 'Small indoor restaurant — step-free entrance.',
      faq: [
        { q: 'Do I need to reserve?', a: 'Yes — absolutely essential. Often fully booked 2–3 days ahead in high season.' },
      ],
      languages: ['en', 'it', 'de'],
    },
    {
      name: 'Downtown Restaurant & Bar',
      type: 'International & Bar',
      desc: 'Central El Gouna gathering spot. Open all day from breakfast to late cocktails. Great people-watching. Mix of expats, tourists, and local El Gouna residents. Reliable menu, consistent quality.',
      area: 'El Gouna Downtown Square',
      hours: '08:00–01:00 daily',
      price_range: '120–300 EGP per person',
      price_usd: '$2.5–6',
      phone: '+20 65 358 0150',
      website: '',
      rating: 4.4,
      verified: true,
      features: ['All-day dining', 'Bar', 'People-watching', 'English-friendly'],
      highlights: ['Open from breakfast to midnight', 'Central location', 'Great cocktails'],
      accessibility: 'Ground-level outdoor seating. Fully accessible.',
      faq: [],
      languages: ['en', 'de', 'ru'],
    },
  ],

  bars_nightlife: [
    {
      name: 'Mango Bar (Abu Tig Marina)',
      type: 'Marina Bar',
      desc: 'El Gouna\'s most famous bar. On the Abu Tig Marina waterfront. Open until very late. Hub of El Gouna social life for expats and long-stay tourists. Excellent cocktails. DJ Thursday–Saturday.',
      area: 'Abu Tig Marina',
      hours: '18:00–03:00, DJ nights Thu–Sat',
      price_range: '80–200 EGP per drink',
      price_usd: '$1.5–4',
      phone: '+20 65 358 0400',
      website: '',
      rating: 4.7,
      verified: true,
      features: ['DJ nights', 'Marina view', 'Late night', 'Cocktails'],
      highlights: ['El Gouna\'s social hub', 'Marina waterfront', 'Best cocktails in town'],
      accessibility: 'Outdoor marina-level bar. Step-free access.',
      safety_rating: 'safe',
      faq: [
        { q: 'Is there a dress code?', a: 'Smart casual. No flip-flops after 9pm on DJ nights.' },
      ],
    },
    {
      name: 'Orca Beach Club',
      type: 'Beach Club & Bar',
      desc: 'Full-day beach club with sun loungers, pool, bar, and restaurant. Famous evening parties in high season. DJ events, fire shows, and themed nights. Most popular beach party venue in El Gouna.',
      area: 'El Gouna Beach',
      hours: '10:00–02:00 (parties until 04:00)',
      price_range: 'Entry: 200–500 EGP (includes drink credit)',
      price_usd: '$4–10',
      phone: '+20 65 358 0500',
      website: 'orcabeachclub.com',
      rating: 4.5,
      verified: true,
      features: ['Beach', 'Pool', 'DJ', 'Themed nights', 'Fire show'],
      highlights: ['Best parties in El Gouna', 'Pool & beach combo', 'Fire shows'],
      accessibility: 'Beach club — sandy access. Some areas wheelchair accessible.',
      safety_rating: 'safe',
      faq: [
        { q: 'Is advance booking needed?', a: 'Yes for special event nights. Walk-in on regular nights.' },
      ],
    },
    {
      name: 'Hemingway Bar',
      type: 'Classic Bar',
      desc: 'Long-running El Gouna institution. Classic bar atmosphere. Excellent whiskeys and spirits selection. Quiet enough for conversation. Popular with European long-stays and sailing crowd.',
      area: 'El Gouna Downtown',
      hours: '17:00–02:00 daily',
      price_range: '60–180 EGP per drink',
      price_usd: '$1.2–3.5',
      phone: '+20 65 358 0450',
      website: '',
      rating: 4.5,
      verified: true,
      features: ['Classic bar', 'Spirits selection', 'No DJ noise', 'English-speaking staff'],
      highlights: ['Best whiskey selection in El Gouna', 'Quiet atmosphere', 'Long-stay favorite'],
      accessibility: 'Indoor bar — step-free entrance.',
      safety_rating: 'safe',
      faq: [],
    },
    {
      name: 'La Luna Rooftop Bar',
      type: 'Rooftop Bar',
      desc: 'Elevated rooftop bar above El Gouna Downtown. 360° views of the lagoons and islands. Perfect for sunset drinks. Intimate atmosphere. Wine and cocktails focus. Popular with couples.',
      area: 'El Gouna Downtown',
      hours: '16:00–01:00 daily',
      price_range: '80–220 EGP per drink',
      price_usd: '$1.5–4.5',
      phone: '+20 65 358 0480',
      website: '',
      rating: 4.6,
      verified: true,
      features: ['Rooftop', '360° views', 'Couples-friendly', 'Wine selection'],
      highlights: ['Best sunset view in downtown', 'Romantic setting', 'Lagoon panorama'],
      accessibility: 'Rooftop via elevator. Fully accessible.',
      safety_rating: 'safe',
      faq: [],
    },
    {
      name: 'Tamr Henna Beach Bar',
      type: 'Beachfront Bar',
      desc: 'Low-key beachfront bar at El Gouna\'s main public beach. Relaxed daytime crowd. Cold drinks, shisha, light snacks. More laid-back than Orca. Better for afternoon unwinding than late-night parties.',
      area: 'El Gouna Main Beach',
      hours: '10:00–23:00 daily',
      price_range: '50–150 EGP per drink',
      price_usd: '$1–3',
      phone: '',
      website: '',
      rating: 4.2,
      verified: false,
      features: ['Beachfront', 'Shisha', 'Relaxed vibe', 'Daytime crowd'],
      highlights: ['Most relaxed bar in El Gouna', 'Great for afternoon drinks', 'Beach access'],
      accessibility: 'Sandy beach bar — accessible with assistance.',
      safety_rating: 'safe',
      faq: [],
    },
  ],

  medical: [
    {
      name: 'El Gouna Hospital (Hayah Hospital)',
      type: 'Full Hospital',
      desc: 'The only full-service hospital in El Gouna. Operated to international standards. 24/7 emergency. English and German-speaking doctors. Accepts all major travel insurance. Hyperbaric chamber for diving injuries on-site.',
      area: 'El Gouna Town Center',
      hours: '24/7 Emergency · Outpatient: 08:00–20:00',
      price_range: 'Consultation: 350–700 EGP',
      price_usd: '$7–14',
      phone: '+20 65 358 0012',
      website: 'hayahhospital.com',
      rating: 4.7,
      verified: true,
      features: ['24/7 emergency', 'Hyperbaric chamber', 'Insurance accepted', 'English & German doctors', 'Diving emergency specialist'],
      highlights: ['Only hospital in El Gouna', 'Diving decompression specialist', 'International standards'],
      accessibility: 'Fully accessible. Wheelchair ramps, lifts.',
      faq: [
        { q: 'Is there a hyperbaric chamber?', a: 'Yes — El Gouna Hospital has one of the best dive injury facilities on the Red Sea coast.' },
        { q: 'What insurance is accepted?', a: 'Most major international insurers. Bring your policy number and emergency contact.' },
      ],
    },
    {
      name: 'El Gouna Pharmacy (Downtown)',
      type: 'Pharmacy',
      desc: 'Main pharmacy in El Gouna Downtown. Wide selection of European medications. English-speaking staff. Accepts prescriptions in Arabic, English, and German. Stocks sunscreen, rehydration salts, and dive medicine.',
      area: 'El Gouna Downtown',
      hours: '09:00–23:00 daily',
      price_range: 'Medication from 30 EGP',
      price_usd: 'from $0.6',
      phone: '+20 65 358 0020',
      website: '',
      rating: 4.5,
      verified: true,
      features: ['English-speaking', 'European medications', 'German prescriptions accepted', 'Extended hours'],
      highlights: ['Best-stocked pharmacy in El Gouna', 'German and English staff', 'Dive medicine available'],
      accessibility: 'Ground floor. Step-free entrance.',
      faq: [],
    },
    {
      name: 'Pro Dive Hyperbaric Center',
      type: 'Diving Medical Specialist',
      desc: 'Specialist hyperbaric medicine center for diving injuries. Decompression sickness treatment. Works closely with El Gouna Hospital. Know this address before you dive.',
      area: 'Adjacent to El Gouna Marina',
      hours: '24/7 for emergencies',
      price_range: 'Hyperbaric treatment: from 4,500 EGP',
      price_usd: 'from $90',
      phone: '+20 65 358 0015',
      website: '',
      rating: 4.9,
      verified: true,
      features: ['24/7 emergency', 'Hyperbaric specialist', 'PADI-affiliated', 'Diving injury expertise'],
      highlights: ['Critical resource for divers', 'Only specialist center in El Gouna', 'Works with all dive centers'],
      accessibility: 'Ground floor clinic. Fully accessible.',
      faq: [
        { q: 'When should I call them?', a: 'If you have ANY symptoms after diving: dizziness, pain, tingling — call immediately. Do not wait.' },
      ],
    },
    {
      name: 'El Gouna Dental Center',
      type: 'Dental Clinic',
      desc: 'Private dental clinic in El Gouna Downtown. European-trained dentist. Walk-ins accepted for emergencies. Full range of dental services. Significantly cheaper than European prices.',
      area: 'El Gouna Downtown',
      hours: '09:00–18:00 Sat–Thu',
      price_range: 'Consultation: 300 EGP, Treatment from 500 EGP',
      price_usd: '$6–10+',
      phone: '+20 65 358 0025',
      website: '',
      rating: 4.4,
      verified: true,
      features: ['English-speaking dentist', 'Walk-ins for emergencies', 'European-trained', 'Cards accepted'],
      highlights: ['Only dedicated dental clinic in El Gouna', 'Emergency appointments available'],
      accessibility: 'Ground floor. Step-free.',
      faq: [],
    },
    {
      name: 'El Gouna Physiotherapy & Sports Clinic',
      type: 'Physiotherapy',
      desc: 'Sports and physiotherapy clinic catering to the active El Gouna crowd — kitesurfers, divers, cyclists, golfers. Sports injury assessment, massage therapy, and rehabilitation.',
      area: 'El Gouna Sports Hub',
      hours: '08:00–20:00 daily',
      price_range: 'Session: 600–1,200 EGP',
      price_usd: '$12–24',
      phone: '+20 65 358 0030',
      website: '',
      rating: 4.5,
      verified: true,
      features: ['Sports injury', 'Kite injury specialist', 'Massage therapy', 'English-speaking'],
      highlights: ['Specialist for kite and watersport injuries', 'Experienced with diving-related muscle issues'],
      accessibility: 'Ground floor. Step-free.',
      faq: [],
    },
  ],

  kids_family: [
    {
      name: 'El Gouna Aqua Park',
      type: 'Water Park',
      desc: 'El Gouna\'s main water park with slides, lazy river, and wave pool. Perfect for families with children of all ages. Full day out. Staff supervision throughout. Café on site.',
      area: 'El Gouna East',
      hours: '10:00–18:00 daily (Oct–May), 09:00–19:00 (Jun–Sep)',
      price_range: 'Adults: 500 EGP · Children (4–12): 300 EGP · Under 4: Free',
      price_usd: '$6–10',
      phone: '+20 65 358 0600',
      website: 'elgouna.com',
      rating: 4.4,
      verified: true,
      features: ['Family-friendly', 'All ages', 'Supervised', 'Café on site', 'Shaded areas'],
      highlights: ['Best family day out in El Gouna', 'Wave pool + slides + lazy river', 'Life jackets provided'],
      accessibility: 'Partially accessible. Main pool areas are step-free.',
      faq: [
        { q: 'Is there a height restriction for the slides?', a: 'Yes — minimum 110cm for the big slides. Smaller slides for younger children.' },
      ],
    },
    {
      name: 'El Gouna Golf Club (Kids Golf)',
      type: 'Golf & Mini Golf',
      desc: 'International 18-hole golf course with a dedicated 9-hole junior course and mini golf area. Golf lessons for children from age 6. Stunning views over lagoons. Proper restaurant on site.',
      area: 'El Gouna Golf Resort',
      hours: '06:30–18:00 daily',
      price_range: 'Junior lessons: 600 EGP · Mini Golf: 150 EGP',
      price_usd: '$3–12',
      phone: '+20 65 358 0700',
      website: 'elgounagolf.com',
      rating: 4.6,
      verified: true,
      features: ['Junior golf', 'Mini golf', 'Family-friendly', 'Restaurant on site', 'English-speaking pros'],
      highlights: ['Only international golf course on the Red Sea', 'Junior lessons available', 'Lagoon views'],
      accessibility: 'Golf buggies available. Accessible clubhouse.',
      faq: [
        { q: 'Do children need experience to play?', a: 'No — junior lessons available from scratch. Minimum age 6 for lessons.' },
      ],
    },
    {
      name: 'Happy Land El Gouna',
      type: 'Kids Entertainment Center',
      desc: 'Indoor kids entertainment center in El Gouna Downtown. Bouncy castles, trampolines, arcade games, and arts & crafts. Perfect for afternoons when it\'s too hot to be outside.',
      area: 'El Gouna Downtown',
      hours: '10:00–22:00 daily',
      price_range: '150–250 EGP per child (2 hours)',
      price_usd: '$3–5',
      phone: '+20 65 358 0650',
      website: '',
      rating: 4.3,
      verified: true,
      features: ['Indoor AC', 'All ages', 'Supervised', 'Arts & crafts', 'Arcade games'],
      highlights: ['Only indoor kids center in El Gouna', 'Perfect for midday heat', 'Staff supervision'],
      accessibility: 'Ground floor. Fully accessible.',
      faq: [],
    },
    {
      name: 'El Gouna Horse Riding',
      type: 'Horse Riding',
      desc: 'Guided horse rides through El Gouna\'s desert trails and lagoon paths. Children and beginner sessions available. Sunset desert rides are spectacular. Fully helmeted and supervised.',
      area: 'Desert outskirts of El Gouna',
      hours: '07:00–10:00 and 15:00–18:00 (early and late to avoid heat)',
      price_range: '400–700 EGP per person (1 hour)',
      price_usd: '$8–14',
      phone: '+20 100 358 0750',
      website: '',
      rating: 4.5,
      verified: true,
      features: ['Children welcome (from age 4)', 'Helmets provided', 'English-speaking guide', 'Beginner-friendly'],
      highlights: ['Sunset desert rides', 'Lagoon trail option', 'Very photogenic'],
      accessibility: 'Desert terrain — not wheelchair accessible.',
      faq: [
        { q: 'What age can children start?', a: 'From age 4 with a parent. From age 8 independently on quiet trails.' },
      ],
    },
    {
      name: 'Snorkeling Family Tour (El Gouna Reef)',
      type: 'Snorkeling & Marine Activity',
      desc: 'Family boat trip to El Gouna\'s pristine coral reefs. Shallow reef entry for beginners and children. Life jackets and snorkel equipment provided. Certified guide. Includes lunch on boat.',
      area: 'El Gouna Marina departure',
      hours: 'Departures: 09:00 daily',
      price_range: 'Adults: 550 EGP · Children (4–12): 300 EGP',
      price_usd: '$6–11',
      phone: '+20 65 358 0800',
      website: '',
      rating: 4.7,
      verified: true,
      features: ['Family-friendly', 'Life jackets', 'Certified guide', 'Lunch included', 'Shallow reef option'],
      highlights: ['Pristine El Gouna reef', 'Ideal for first-timers', 'Protected lagoon area for children'],
      accessibility: 'Boat access via marina — steps to board. Life jackets for all.',
      faq: [
        { q: 'Can non-swimmers join?', a: 'Yes — life jackets provided and guide stays with non-swimmers near the boat.' },
      ],
    },
  ],

  beaches_water: [
    {
      name: 'Kite Beach El Gouna',
      type: 'Kite & Wind Sports Beach',
      desc: 'World-class kitesurfing beach. Consistent strong winds make it one of the top 10 kite spots on earth. IKO-certified schools on the beach. Shallow flat water — ideal for beginners. Annual international kite events held here.',
      area: 'El Gouna North — 3km from Downtown',
      hours: 'Open all day — wind strongest 10:00–17:00',
      price_range: 'Kitesurfing lesson (3hrs): 1,600 EGP · Equipment rental: 800 EGP/day',
      price_usd: '$16–32',
      phone: '+20 65 358 0900',
      website: 'kitesurfingelgouna.com',
      rating: 4.9,
      verified: true,
      features: ['IKO certified schools', 'Equipment rental', 'Beginner-friendly', 'Flat water', 'Windsurfing also'],
      highlights: ['Top 10 kite spot globally', 'Annual Kite Festival', 'IKO and VDWS certified instructors'],
      accessibility: 'Sandy beach. Narrow access road. Not wheelchair accessible to the water.',
      faq: [
        { q: 'When is the best kite season?', a: 'October–May: strongest and most consistent winds. June–September is possible but lighter winds.' },
        { q: 'Do I need experience?', a: 'No — IKO-certified beginners courses start from zero. Day 1 is theory and beach training.' },
      ],
    },
    {
      name: 'Mangroovy Beach',
      type: 'Public Beach & Lagoon',
      desc: 'El Gouna\'s most popular day beach. Calm, protected lagoon waters — ideal for families and swimmers. Sunbeds available. Bar on site. Windsurfing and stand-up paddleboarding rental.',
      area: 'El Gouna Lagoon Area',
      hours: '09:00–20:00 daily',
      price_range: 'Entry: 100 EGP · Sunbed: 80 EGP · SUP rental: 200 EGP/hour',
      price_usd: '$2–4',
      phone: '+20 65 358 0950',
      website: '',
      rating: 4.5,
      verified: true,
      features: ['Calm lagoon', 'Family-friendly', 'SUP rental', 'Bar on site', 'Sunbeds'],
      highlights: ['Safest swimming in El Gouna', 'Flat calm water', 'Great for kids and non-swimmers'],
      accessibility: 'Beach access via sandy path. Sunbeds available at the waterline.',
      faq: [],
    },
    {
      name: 'Giftun Island Boat Trip (from El Gouna)',
      type: 'Day Boat Trip',
      desc: 'Full-day boat excursion from El Gouna Marina to Giftun Island. Some of the Red Sea\'s finest coral reefs. Lunch on board. Snorkeling equipment included. 45-minute boat ride each way.',
      area: 'Departing from El Gouna Marina',
      hours: 'Departure: 09:00 · Return: 16:00',
      price_range: '800–1,100 EGP per person (all-inclusive)',
      price_usd: '$16–22',
      phone: '+20 65 358 1000',
      website: '',
      rating: 4.8,
      verified: true,
      features: ['All-inclusive', 'Snorkeling gear', 'Lunch included', 'Marine guide', 'Life jackets'],
      highlights: ['World-class Giftun reef', 'Pristine coral gardens', 'Dolphins frequently spotted'],
      accessibility: 'Boat boarding via marina steps. Life jackets for all.',
      faq: [
        { q: 'How far is Giftun from El Gouna?', a: '45 minutes by speedboat. Boat conditions are calm in season (Oct–May).' },
      ],
    },
    {
      name: 'El Gouna Diving Center',
      type: 'Scuba Diving',
      desc: 'PADI 5-star dive center in Abu Tig Marina. Day dives to Shaab Sharm and El Fanous reefs — some of the Red Sea\'s most pristine dive sites. PADI courses from Discover Scuba to Divemaster.',
      area: 'Abu Tig Marina',
      hours: 'Departures: 08:30 and 13:00 daily',
      price_range: '2 dives with equipment: 2,000 EGP · PADI Open Water course: 6,000 EGP',
      price_usd: '$38–113',
      phone: '+20 65 358 1100',
      website: 'elgounadiving.com',
      rating: 4.8,
      verified: true,
      features: ['PADI 5-star', 'All equipment included', 'Beginner courses', 'Experienced crew', 'Nitrox available'],
      highlights: ['Access to El Gouna\'s exclusive reefs', 'Small group dives', 'Camera rental available'],
      accessibility: 'Marina-based. Boat boarding via steps.',
      faq: [
        { q: 'What reefs do you visit?', a: 'Shaab Sharm, El Fanous, and Umm Qamar — all within 30 min boat ride and exclusive to El Gouna operators.' },
      ],
    },
    {
      name: 'Stand-Up Paddleboard & Kayak Rental',
      type: 'Watersports Rental',
      desc: 'Self-guided paddleboard and kayak rental in El Gouna\'s calm lagoons. Navigate between islands at your own pace. Ideal for early mornings when the water is mirror-flat. No experience needed.',
      area: 'Mangroovy Beach & Downtown Lagoon',
      hours: '08:00–18:00 daily',
      price_range: 'SUP: 200 EGP/hour · Kayak: 150 EGP/hour',
      price_usd: '$3–4/hour',
      phone: '+20 65 358 1150',
      website: '',
      rating: 4.5,
      verified: true,
      features: ['No experience needed', 'Calm lagoon', 'Self-guided', 'Life jackets included'],
      highlights: ['Explore the islands at your own pace', 'Flat calm water', 'Sunrise sessions available'],
      accessibility: 'Launched from sandy beach — step-free water entry.',
      faq: [],
    },
  ],

  museums_culture: [
    {
      name: 'El Gouna Museum',
      type: 'Local History & Art Museum',
      desc: 'Small but interesting museum documenting the history of El Gouna\'s construction from a fishing village into a city. Architectural models, original design drawings, and local photography collection.',
      area: 'El Gouna Downtown',
      hours: '10:00–18:00 Sat–Thu',
      price_range: 'Entry: 50 EGP',
      price_usd: '$1',
      phone: '+20 65 358 1200',
      website: '',
      rating: 4.1,
      verified: true,
      features: ['English captions', 'Air-conditioned', 'Photography allowed', 'Small group friendly'],
      highlights: ['How El Gouna was built', 'Architectural history', 'Local artist gallery section'],
      accessibility: 'Ground floor. Fully accessible.',
      faq: [],
    },
    {
      name: 'El Gouna Art Gallery (Downtown)',
      type: 'Contemporary Art Gallery',
      desc: 'Rotating exhibitions of Egyptian and international contemporary art. Supported by the El Gouna Film Festival organization. Exhibitions change monthly. Free entry.',
      area: 'El Gouna Downtown',
      hours: '11:00–20:00 Tue–Sun',
      price_range: 'Free',
      price_usd: 'Free',
      phone: '+20 65 358 1210',
      website: '',
      rating: 4.3,
      verified: true,
      features: ['Free entry', 'AC', 'Contemporary art', 'Egyptian artists featured'],
      highlights: ['Free and high-quality exhibitions', 'Often tied to El Gouna Film Festival', 'Local artists spotlight'],
      accessibility: 'Ground floor gallery. Fully accessible.',
      faq: [],
    },
    {
      name: 'El Gouna Film Festival Venues',
      type: 'Cultural Event',
      desc: 'El Gouna hosts one of the Middle East\'s most prestigious film festivals annually (usually October). Screenings, talks, and events across multiple venues including the open-air Abu Tig Marina.',
      area: 'Various El Gouna venues',
      hours: 'Annual — October (check schedule)',
      price_range: 'Passes: 500–2,000 EGP · Individual screenings: 100 EGP',
      price_usd: '$2–40',
      phone: '',
      website: 'elgounafilmfestival.com',
      rating: 4.8,
      verified: true,
      features: ['World-class cinema', 'Red carpet events', 'Celebrity appearances', 'Open-air screenings'],
      highlights: ['Middle East\'s premier film festival', 'International stars attend', 'Open-air marina screenings'],
      accessibility: 'Multiple venues — varies. Marina venue is step-free.',
      faq: [
        { q: 'When is El Gouna Film Festival?', a: 'Usually October. Check the official website 2 months before your trip.' },
      ],
    },
    {
      name: 'Pharaonic Village Day Trip (Luxor)',
      type: 'Historical Day Trip',
      desc: 'For guests staying longer in El Gouna, Luxor is 3 hours north by road. Private car day trips can be arranged. Valley of the Kings, Karnak, and Luxor Temple are accessible for a full-day excursion.',
      area: 'Luxor — 3hr drive north',
      hours: 'Full day: depart 06:00, return 20:00',
      price_range: 'Private car + guide: 4,500–6,000 EGP (group)',
      price_usd: '$90–120 (group)',
      phone: '+20 100 358 1300',
      website: '',
      rating: 4.9,
      verified: true,
      features: ['Private car', 'Licensed Egyptologist guide', 'All entry tickets included', 'AC transport'],
      highlights: ['Only way to see Luxor from El Gouna in one day', 'Expert guide', 'Full historical immersion'],
      accessibility: 'AC car. Temple sites have some accessibility — Valley of Kings is uneven terrain.',
      faq: [
        { q: 'Is it worth the drive?', a: 'Absolutely yes. Luxor is the greatest open-air museum in the world. The 3-hour drive is worth it.' },
      ],
    },
    {
      name: 'El Gouna Golf Course Tour',
      type: 'Architecture & Design Tour',
      desc: 'Guided tour of El Gouna\'s unique island city architecture. Robert Trent Jones Jr. designed golf course set among lagoons. Tour includes design history, sustainable architecture notes, and course walk.',
      area: 'El Gouna Golf Resort',
      hours: 'Tours: 09:00 and 15:00 Mon, Wed, Sat',
      price_range: '300 EGP per person',
      price_usd: '$6',
      phone: '+20 65 358 0700',
      website: 'elgounagolf.com',
      rating: 4.4,
      verified: false,
      features: ['Architecture focus', 'English-speaking guide', 'Small groups', 'Includes golf buggy'],
      highlights: ['Unique sustainable city design', 'Red Sea lagoon panorama', 'Behind-the-scenes of El Gouna\'s creation'],
      accessibility: 'Golf buggy transport. Clubhouse fully accessible.',
      faq: [],
    },
  ],

  remote_work: [
    {
      name: 'The Hub El Gouna (Co-working)',
      type: 'Coworking Space',
      desc: 'El Gouna\'s dedicated co-working space. Part of a Sahara Ventures initiative. High-speed fiber internet (100Mbps+), meeting rooms, printing, and standing desks. Strong startup and freelancer community.',
      area: 'El Gouna Downtown',
      hours: '08:00–20:00 Sat–Thu',
      price_range: 'Day pass: 300 EGP · Monthly: 2,500 EGP',
      price_usd: '$6/day · $50/month',
      phone: '+20 65 358 1400',
      website: 'hubgouna.com',
      rating: 4.7,
      verified: true,
      features: ['100Mbps+ fiber', 'Meeting rooms', 'Standing desks', 'Printing', 'AC', 'Coffee included'],
      highlights: ['Best internet in El Gouna', 'Startup community', 'Event space available'],
      accessibility: 'Ground floor. Fully accessible.',
      faq: [
        { q: 'Is internet reliable for video calls?', a: 'Yes — fiber internet, stable for Zoom and large file transfers. Backup 4G available.' },
      ],
    },
    {
      name: 'Abu Tig Marina Cafés (Remote Work Friendly)',
      type: 'Café with WiFi',
      desc: 'Several marina-front cafés offer good WiFi and don\'t rush customers. Best for morning work sessions: La Cantina and Downtown Café both have reliable connections and power outlets at most tables.',
      area: 'Abu Tig Marina',
      hours: '08:00–22:00 daily',
      price_range: 'Coffee: 60–100 EGP (expect to spend 150+ EGP for a work session)',
      price_usd: '$1.2–2/coffee',
      phone: '',
      website: '',
      rating: 4.3,
      verified: false,
      features: ['WiFi', 'Power outlets', 'Marina view', 'AC inside', 'No time pressure'],
      highlights: ['Best atmosphere for working remotely', 'Marina views', 'Coffee quality is good'],
      accessibility: 'Ground floor cafés. Fully accessible.',
      faq: [],
    },
    {
      name: 'El Gouna Hotel Business Centers',
      type: 'Hotel Business Facility',
      desc: 'Most El Gouna 4-5 star hotels offer business center access to guests. Sheraton El Gouna and Mövenpick have the best-equipped facilities with reliable fiber, printers, and private meeting rooms.',
      area: 'Various hotel properties',
      hours: 'Varies by hotel (typically 08:00–22:00)',
      price_range: 'Free for hotel guests · Day pass: 200–400 EGP for non-guests',
      price_usd: '$4–8',
      phone: '+20 65 354 5845',
      website: 'marriott.com',
      rating: 4.4,
      verified: true,
      features: ['Fiber internet', 'Private rooms', 'Printing', 'Professional setting', 'AC'],
      highlights: ['Most private option for important calls', 'Professional infrastructure', 'Secure connections'],
      accessibility: 'Hotel business centers are fully accessible.',
      faq: [],
    },
    {
      name: 'Vodafone & Orange Official Stores (El Gouna)',
      type: 'SIM & Internet Services',
      desc: 'Both Vodafone and Orange have official stores near El Gouna Downtown. Best SIM deals for remote workers: Vodafone 40GB (250 EGP) or e& 50GB (210 EGP). 4G speeds good throughout El Gouna.',
      area: 'El Gouna Downtown (near main roundabout)',
      hours: '10:00–21:00 Sat–Thu',
      price_range: 'SIM from 115 EGP · 40GB data: 250 EGP',
      price_usd: '$2.3–5',
      phone: '',
      website: 'vodafone.com.eg',
      rating: 4.5,
      verified: true,
      features: ['Official store', 'English-speaking staff', '4G throughout El Gouna', 'Best data prices'],
      highlights: ['Buy official — not at airport', 'Vodafone has best El Gouna coverage', '40GB for $5'],
      accessibility: 'Ground floor stores.',
      faq: [
        { q: 'Is 4G reliable in El Gouna?', a: 'Yes — Vodafone and Orange both have strong 4G in El Gouna Downtown, marina, and kite beach areas.' },
      ],
    },
    {
      name: 'El Gouna Public Library (Reading & Quiet Work)',
      type: 'Library & Quiet Space',
      desc: 'Small public library in El Gouna. AC, quiet, WiFi. Good for focused reading or writing. Limited opening hours. Small tech collection. Also used for community events.',
      area: 'El Gouna Central Area',
      hours: '09:00–14:00 Sat–Wed',
      price_range: 'Free',
      price_usd: 'Free',
      phone: '+20 65 358 1450',
      website: '',
      rating: 4.0,
      verified: false,
      features: ['Free', 'AC', 'WiFi', 'Quiet', 'Reading space'],
      highlights: ['Quietest work spot in El Gouna', 'Free and welcoming', 'Good for morning focus sessions'],
      accessibility: 'Ground floor. Fully accessible.',
      faq: [],
    },
  ],

  transport: [
    {
      name: 'El Gouna Tuk-Tuk (Official)',
      type: 'City Tuk-Tuk',
      desc: 'El Gouna\'s unique transport system: branded electric and gas tuk-tuks connecting all areas of the city. This is how most residents and tourists get around. Available 24 hours.',
      area: 'Citywide — pick up anywhere',
      hours: '24/7',
      price_range: '30–100 EGP per trip (depending on distance)',
      price_usd: '$0.6–2',
      phone: '+20 65 358 1500 (dispatch)',
      website: '',
      rating: 4.5,
      verified: true,
      features: ['24/7 service', 'City-wide coverage', 'Fixed rates between areas', 'Electric and gas options'],
      highlights: ['Primary transport in El Gouna', 'Faster than walking between islands', 'Can be shared'],
      accessibility: 'Step up to board. Not wheelchair accessible.',
      faq: [
        { q: 'How do I get a tuk-tuk?', a: 'Hail one from any road (they are everywhere) or call the dispatch number. Agree price before departing.' },
        { q: 'Are there fixed prices?', a: 'Approximate fixed routes exist but negotiate in EGP before boarding.' },
      ],
    },
    {
      name: 'El Gouna Bus (Free Shuttle)',
      type: 'Free Hotel Shuttle Bus',
      desc: 'El Gouna operates a free shuttle bus connecting hotels, downtown, marina, and beach areas. Runs on a fixed timetable. Best for non-time-sensitive travel between zones.',
      area: 'Citywide shuttle route',
      hours: 'Every 30–60 min, 07:00–23:00',
      price_range: 'Free for El Gouna visitors',
      price_usd: 'Free',
      phone: '+20 65 358 1550',
      website: 'elgouna.com/transport',
      rating: 4.2,
      verified: true,
      features: ['Free', 'Regular schedule', 'AC', 'Covers all major areas'],
      highlights: ['Best free transport in any Egyptian resort', 'Connects all hotels to downtown and beaches'],
      accessibility: 'Low-floor bus. Wheelchair accessible with assistance.',
      faq: [
        { q: 'Where can I get the timetable?', a: 'From your hotel reception or the El Gouna Tourism Office in downtown.' },
      ],
    },
    {
      name: 'Hurghada to El Gouna Transfer',
      type: 'Airport & City Transfer',
      desc: 'El Gouna is 30km north of Hurghada. Shared taxis and private cars connect Hurghada Airport to El Gouna directly. Pre-book for the fixed rate. Uber/Careem does not operate in El Gouna.',
      area: 'Hurghada Airport → El Gouna',
      hours: '24/7 (book ahead for night arrivals)',
      price_range: 'Private car: 350–500 EGP · Shared taxi: 100–150 EGP per person',
      price_usd: '$2–10',
      phone: '+20 65 358 1600',
      website: '',
      rating: 4.3,
      verified: true,
      features: ['Pre-book recommended', 'Private and shared options', 'Fixed rates available', 'AC cars'],
      highlights: ['Only land connection to El Gouna', '30-minute drive', 'Pre-book avoids airport touts'],
      accessibility: 'AC cars. Luggage assistance available.',
      faq: [
        { q: 'How far is Hurghada Airport from El Gouna?', a: '30km — approximately 30 minutes by car.' },
        { q: 'Can I take an Uber?', a: 'Uber and Careem operate from Hurghada city but do not enter El Gouna. Pre-arrange your transfer.' },
      ],
    },
    {
      name: 'El Gouna Boat Taxi (Lagoon)',
      type: 'Water Taxi',
      desc: 'Small motorboats acting as water taxis across El Gouna\'s lagoon network. Fastest way to reach some islands. Operate mainly morning and evening. Hail from any lagoon dock.',
      area: 'El Gouna Lagoon Network',
      hours: '07:00–22:00 (irregular — on demand)',
      price_range: '20–50 EGP per crossing',
      price_usd: '$0.4–1',
      phone: '',
      website: '',
      rating: 4.4,
      verified: false,
      features: ['Scenic', 'Fast island-to-island', 'On demand', 'Cash only'],
      highlights: ['Only way to cross some lagoons quickly', 'Scenic route between islands', 'Unique El Gouna experience'],
      accessibility: 'Small boat — step down to board. Not wheelchair accessible.',
      faq: [],
    },
    {
      name: 'El Gouna Bicycle & Golf Cart Rental',
      type: 'Self-Drive Rental',
      desc: 'Bicycle and golf cart rental is popular in El Gouna. The city is designed to be cycle-friendly with bike paths connecting most areas. Golf carts can be rented for half or full days.',
      area: 'Available from most hotels and downtown rental shops',
      hours: '08:00–20:00 daily',
      price_range: 'Bicycle: 100–150 EGP/day · Golf cart: 600–900 EGP/day',
      price_usd: '$2–18/day',
      phone: '+20 65 358 1650',
      website: '',
      rating: 4.5,
      verified: true,
      features: ['Cycle paths', 'Self-guided', 'Flat terrain', 'Maps provided', 'Golf cart option'],
      highlights: ['Best way to explore El Gouna independently', 'Cycle-friendly city design', 'Flat and lagoon-path routes'],
      accessibility: 'Flat terrain — bicycle paths accessible. Golf carts accessible.',
      faq: [
        { q: 'Is El Gouna safe to cycle?', a: 'Yes — traffic is very light compared to Egyptian cities. Dedicated paths in most areas.' },
      ],
    },
  ],
};

// Hotels for all cities
export const HOTELS_BY_CITY = {
  hurghada: [
    {
      name: 'Steigenberger ALDAU Beach Hotel',
      type: '5-Star Luxury Resort',
      desc: 'Hurghada\'s flagship luxury resort. Pristine private beach on a protected coral bay. Spectacular pools, world-class spa, and award-winning restaurants. The benchmark of quality on the Red Sea.',
      area: 'ALDAU Heights, South Hurghada',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 9500, price_usd_night: 179,
      phone: '+20 65 346 5400',
      website: 'https://www.steigenbergeraldauresort.com',
      rating: 4.8,
      verified: true,
      features: ['Private coral beach', 'Spa', 'Multiple pools', 'WiFi', 'Fine dining', 'Dive center', 'Kids club'],
      photos: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Steigenberger_Aldau_Hotel_Hurghada.jpg/960px-Steigenberger_Aldau_Hotel_Hurghada.jpg',
        'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
      ],
      faq: [{ q: 'Is the beach private?', a: 'Yes — exclusive coral beach, no public access. Some of the clearest water in Hurghada.' }],
    },
    {
      name: 'Sunrise Crystal Bay Resort',
      type: '5-Star All-Inclusive',
      desc: 'Award-winning all-inclusive on a stunning crystal-clear bay. Beautiful reef right off the beach. Multiple restaurants, aqua park, and nightly entertainment. Consistently top-rated in Hurghada.',
      area: 'Sahl Hasheesh, Hurghada',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 6800, price_usd_night: 128,
      phone: '+20 65 346 5000',
      website: 'https://www.sunrise-resorts.com',
      rating: 4.7,
      verified: true,
      features: ['All-inclusive', 'Crystal bay beach', 'Reef access', 'Aqua park', 'WiFi', 'Multiple restaurants', 'Nightly shows'],
      photos: [
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Jaz Aquamarine Resort',
      type: '5-Star All-Inclusive',
      desc: 'One of Hurghada\'s most popular resorts. Massive aqua park, beautiful beach, and vibrant entertainment. Excellent for families and party-goers alike. Great snorkeling reef directly accessible.',
      area: 'Sahl Hasheesh, Hurghada',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 5500, price_usd_night: 103,
      phone: '+20 65 346 9100',
      website: 'https://www.jazhotels.com',
      rating: 4.6,
      verified: true,
      features: ['All-inclusive', 'Aqua park', 'Private beach', 'WiFi', '8 restaurants', 'Kids animation', 'Nightly entertainment'],
      photos: [
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80',
        'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Titanic Beach Spa & Aqua Park',
      type: '5-Star All-Inclusive',
      desc: 'Large all-inclusive with a well-regarded aqua park and spa. Spacious grounds, excellent pool complex, and reliable food quality. Popular with families and European package tourists.',
      area: 'Sahl Hasheesh, Hurghada',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 5000, price_usd_night: 94,
      phone: '+20 65 346 6000',
      website: 'https://www.titanicgroup.com',
      rating: 4.5,
      verified: true,
      features: ['All-inclusive', 'Aqua park', 'Spa', 'Private beach', 'WiFi', 'Multiple pools', 'Animation team'],
      photos: [
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
        'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
        'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Pickalbatros White Beach Resort',
      type: '5-Star All-Inclusive',
      desc: 'Stunning white sandy beach — one of the best in Hurghada. Excellent snorkeling reef right off the shore. Well-maintained all-inclusive with strong food quality. Very popular with repeat visitors.',
      area: 'Sahl Hasheesh, Hurghada',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 4800, price_usd_night: 90,
      phone: '+20 65 346 4700',
      website: 'https://www.pickalbatros.com',
      rating: 4.6,
      verified: true,
      features: ['White sandy beach', 'Snorkeling reef', 'All-inclusive', 'WiFi', 'Pool complex', 'Spa', 'Multiple restaurants'],
      photos: [
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
        'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=800&q=80',
        'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Baron Palace Sahl Hasheesh',
      type: '5-Star Palace Resort',
      desc: 'Palatial 5-star on the exclusive Sahl Hasheesh bay. Royal architecture, private beach, 14 pools, and a 1.5km lagoon. One of the most extravagant resort experiences in all of Egypt.',
      area: 'Sahl Hasheesh, Hurghada',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 7500, price_usd_night: 141,
      phone: '+20 65 346 6500',
      website: 'https://www.baronhotels.com',
      rating: 4.7,
      verified: true,
      features: ['14 pools', 'Lagoon', 'Private beach', 'Spa', 'WiFi', 'Multiple restaurants', 'Royal architecture'],
      photos: [
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
        'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Desert Rose Resort',
      type: '5-Star Resort',
      desc: 'Elegant resort with a distinctive Arabian-inspired design. Beautiful gardens, pristine beach, and excellent service. More serene than the mega-resorts — ideal for couples and relaxation seekers.',
      area: 'Hurghada coastal strip',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 4500, price_usd_night: 85,
      phone: '+20 65 346 5600',
      website: 'https://www.desertrose.com.eg',
      rating: 4.5,
      verified: true,
      features: ['Arabian design', 'Private beach', 'Gardens', 'Spa', 'WiFi', 'Pool', 'Quiet atmosphere'],
      photos: [
        'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80',
        'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      ],
      faq: [],
    },
  ],
  'el-gouna': [
    {
      name: 'Casa Cook El Gouna',
      type: '5-Star Boutique Resort',
      desc: 'Stylish adults-only boutique resort with a bohemian Mediterranean vibe. Stunning pool terraces, rooftop bar, and direct Red Sea beach access. One of El Gouna\'s most Instagram-worthy hotels.',
      area: 'El Gouna Beach',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 7200, price_usd_night: 135,
      phone: '+20 65 358 0000',
      website: 'https://casacook.com/el-gouna',
      rating: 4.8,
      verified: true,
      features: ['Adults-only', 'Rooftop bar', 'Pool terraces', 'Private beach', 'WiFi', 'Design hotel', 'Spa'],
      photos: [
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
      ],
      faq: [{ q: 'Is it adults-only?', a: 'Yes — Casa Cook is adults-only (16+). Ideal for couples and solo travellers.' }],
    },
    {
      name: "Cook's Club El Gouna",
      type: '4-Star Active Resort',
      desc: 'Energetic, music-forward resort for the younger crowd. DJ pools, watersports, beach parties, and great food. More affordable than the 5-stars while delivering a vibrant experience.',
      area: 'El Gouna Beach',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 4500, price_usd_night: 85,
      phone: '+20 65 358 0100',
      website: 'https://www.cooksclub.com',
      rating: 4.5,
      verified: true,
      features: ['DJ pool', 'Watersports', 'Beach parties', 'All-inclusive option', 'WiFi', 'Young crowd'],
      photos: [
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
        'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&q=80',
        'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Steigenberger Golf Resort El Gouna',
      type: '5-Star Golf Resort',
      desc: 'Elegant 5-star built around El Gouna\'s championship golf course. Lagoon views, award-winning spa, and a peaceful atmosphere away from the party resorts. Ideal for golfers and couples seeking calm luxury.',
      area: 'El Gouna Golf Course',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 6500, price_usd_night: 122,
      phone: '+20 65 358 0200',
      website: 'https://www.steigenberger.com',
      rating: 4.7,
      verified: true,
      features: ['Golf course access', 'Spa', 'Lagoon views', 'Pool', 'WiFi', 'Fine dining', 'Peaceful setting'],
      photos: [
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Sheraton Miramar Resort El Gouna',
      type: '5-Star Island Resort',
      desc: 'Iconic pyramid-shaped hotel on its own island in El Gouna. Award-winning design by Michael Graves. Private beach, 4 pools, 5 restaurants. Considered El Gouna\'s most architecturally distinctive hotel.',
      area: 'Miramar Island, El Gouna',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 5500, price_usd_night: 103,
      phone: '+20 65 354 5845',
      website: 'https://www.marriott.com',
      rating: 4.7,
      verified: true,
      features: ['Private island', '4 pools', 'Private beach', 'WiFi', 'Breakfast included', '5 restaurants', 'Spa', 'Tennis'],
      photos: [
        'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
        'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80',
      ],
      faq: [{ q: 'How do I reach the hotel from El Gouna Downtown?', a: 'Free hotel shuttle + bridge crossing. About 10 min from downtown.' }],
    },
    {
      name: 'Movenpick Resort El Gouna',
      type: '5-Star Resort',
      desc: 'Swiss brand quality on the El Gouna lagoon. Known for its chocolate hour, excellent service, and business facilities. Popular with families and corporate travelers.',
      area: 'El Gouna Lagoon',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 5000, price_usd_night: 94,
      phone: '+20 65 354 4501',
      website: 'https://www.movenpick.com',
      rating: 4.6,
      verified: true,
      features: ['Lagoon view', 'WiFi', 'Pool', 'Breakfast included', 'Business center', 'Spa', 'Kids pool'],
      photos: [
        'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Ancient Sands Resort',
      type: '4-Star Boutique Golf Resort',
      desc: 'Charming boutique resort adjacent to the golf course. Egyptian-inspired architecture with modern comforts. Quiet and green — a peaceful escape ideal for golfers and nature lovers.',
      area: 'El Gouna Golf Area',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 3200, price_usd_night: 60,
      phone: '+20 65 358 0300',
      website: 'https://www.ancientsands.com',
      rating: 4.4,
      verified: true,
      features: ['Golf access', 'Pool', 'Garden', 'WiFi', 'Breakfast included', 'Boutique', 'Quiet atmosphere'],
      photos: [
        'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=800&q=80',
        'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      ],
      faq: [],
    },
  ],
  'sharm-el-sheikh': [
    {
      name: 'Four Seasons Resort Sharm El Sheikh',
      type: '5-Star Luxury',
      desc: 'The finest hotel in Sharm El Sheikh. Private beach on a pristine coral bay. No mass tourism — a genuinely exclusive experience. 5-star across every dimension.',
      area: 'Ras Um Sid, South Sharm',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 17000, price_usd_night: 319,
      phone: '+20 69 360 3555',
      website: 'https://www.fourseasons.com',
      rating: 4.9,
      verified: true,
      features: ['Private coral beach', 'Butler service', 'Spa', 'Multiple pools', 'PADI dive center', 'Kids club', 'WiFi'],
      photos: [
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      ],
      faq: [{ q: 'Is it worth the price?', a: 'Yes, if budget allows. The private beach access to pristine coral reef is unmatched in all of Sharm.' }],
    },
    {
      name: 'Rixos Premium Seagate',
      type: '5-Star Ultra-All-Inclusive',
      desc: 'Ultra-all-inclusive resort at the premium end. Everything truly included: premium spirits, specialty restaurants, entertainment, sports, and kids\' club. Private sandy beach.',
      area: 'Nabq Bay, North Sharm',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 9000, price_usd_night: 169,
      phone: '+20 69 371 2000',
      website: 'https://www.rixos.com',
      rating: 4.7,
      verified: true,
      features: ['Ultra all-inclusive', 'Premium spirits', 'Private beach', 'Spa', '7 restaurants', 'Kids club', 'Waterpark'],
      photos: [
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
        'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&q=80',
        'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Sunrise Arabian Beach Resort',
      type: '5-Star All-Inclusive',
      desc: 'Spectacular beachfront all-inclusive with Arabian architecture and stunning Red Sea views. Excellent snorkeling reef right off the beach. Multiple pools and premium dining.',
      area: 'Naama Bay, Sharm El Sheikh',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 6500, price_usd_night: 122,
      phone: '+20 69 360 2222',
      website: 'https://www.sunrise-resorts.com',
      rating: 4.6,
      verified: true,
      features: ['All-inclusive', 'Reef access', 'Multiple pools', 'Arabian design', 'WiFi', 'Spa', 'Nightly shows'],
      photos: [
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Savoy Sharm El Sheikh',
      type: '5-Star Boutique Resort',
      desc: 'Intimate boutique 5-star with a private sandy cove, lush gardens, and personal service. Less crowded than the mega-resorts. A favorite among repeat visitors who value exclusivity.',
      area: 'South Sharm, White Knight Bay',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 8000, price_usd_night: 150,
      phone: '+20 69 360 1234',
      website: 'https://www.savoy-sharm.com',
      rating: 4.7,
      verified: true,
      features: ['Private beach cove', 'Boutique', 'Gardens', 'Spa', 'WiFi', 'Multiple pools', 'Fine dining'],
      photos: [
        'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
        'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
        'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Sultan Gardens Resort',
      type: '5-Star Garden Resort',
      desc: 'Beautifully landscaped 5-star resort with lush tropical gardens, private beach, and a stunning house reef for snorkeling and diving. A serene alternative to the busy Naama Bay strip.',
      area: 'Sharm el Sheikh',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 5500, price_usd_night: 103,
      phone: '+20 69 366 2800',
      website: 'https://www.sultangardens.com',
      rating: 4.6,
      verified: true,
      features: ['Tropical gardens', 'House reef', 'Private beach', 'Multiple pools', 'Spa', 'WiFi', 'Dive center'],
      photos: [
        'https://images.unsplash.com/photo-1589391886645-d51941baf7fb?w=800&q=80',
        'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=800&q=80',
        'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Baron Resort Sharm El Sheikh',
      type: '5-Star All-Inclusive',
      desc: 'Palatial all-inclusive with an impressive private beach and extensive facilities. Family-friendly with a strong entertainment program, multiple themed restaurants, and a large pool complex.',
      area: 'Sharm El Sheikh',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 6000, price_usd_night: 113,
      phone: '+20 69 366 5858',
      website: 'https://www.baronhotels.com',
      rating: 4.5,
      verified: true,
      features: ['All-inclusive', 'Private beach', 'Multiple pools', 'Kids club', 'WiFi', 'Multiple restaurants', 'Entertainment'],
      photos: [
        'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
      ],
      faq: [],
    },
  ],
  luxor: [
    {
      name: 'Sofitel Winter Palace Luxor',
      type: '5-Star Historic Hotel',
      desc: 'The most famous hotel in Luxor — a Victorian palace built in 1886. Howard Carter planned the discovery of Tutankhamun\'s tomb from this hotel. Lush gardens, Nile views, royal suite.',
      area: 'Corniche El Nil, East Bank',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 10500, price_usd_night: 197,
      phone: '+20 95 238 0422',
      website: 'https://all.accor.com',
      rating: 4.8,
      verified: true,
      features: ['Historic 1886 building', 'Nile view', 'Garden', 'Pool', 'Spa', 'WiFi', 'Fine dining', 'Howard Carter connection'],
      photos: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Winter_Palace_Hotel_Luxor.jpg/960px-Winter_Palace_Hotel_Luxor.jpg',
        'https://images.unsplash.com/photo-1553784538-celdefe3d5b6?w=800&q=80',
        'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80',
      ],
      faq: [{ q: 'Was this really connected to Tutankhamun\'s discovery?', a: 'Yes — Howard Carter and Lord Carnarvon used the Winter Palace as their base. You can see their original rooms.' }],
    },
    {
      name: 'Hilton Luxor Resort & Spa',
      type: '5-Star Nile Resort',
      desc: 'Modern 5-star on the East Bank Nile Corniche. Stunning infinity pool overlooking the Nile. Excellent spa, multiple dining options, and easy access to all major Luxor sights.',
      area: 'Corniche El Nil, East Bank',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 7500, price_usd_night: 141,
      phone: '+20 95 239 9999',
      website: 'https://www.hilton.com',
      rating: 4.7,
      verified: true,
      features: ['Nile infinity pool', 'Spa', 'WiFi', 'Fine dining', 'Fitness center', 'River view rooms', 'Business center'],
      photos: [
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Steigenberger Nile Palace',
      type: '5-Star Resort',
      desc: 'German-managed 5-star on the East Bank Corniche. Large Nile-view rooms. Excellent breakfast. Very reliable service. Popular with European and Russian tour groups.',
      area: 'Corniche El Nil, East Bank',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 6200, price_usd_night: 116,
      phone: '+20 95 236 6999',
      website: 'https://www.steigenberger.com',
      rating: 4.6,
      verified: true,
      features: ['Nile view', 'Pool', 'Spa', 'WiFi', 'Breakfast included', 'German management', 'River cruise booking'],
      photos: [
        'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
        'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80',
        'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Sonesta St. George Hotel Luxor',
      type: '5-Star Hotel',
      desc: 'Elegant 5-star hotel in the heart of Luxor with stunning Nile views. Rooftop pool overlooking the river, multiple restaurants, and walking distance to Luxor Temple.',
      area: 'Corniche El Nil, Luxor',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 5800, price_usd_night: 109,
      phone: '+20 95 238 2575',
      website: 'https://www.sonesta.com',
      rating: 4.5,
      verified: true,
      features: ['Nile view', 'Rooftop pool', 'Multiple restaurants', 'WiFi', 'Spa', 'Central location', 'Breakfast included'],
      photos: [
        'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
        'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
        'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Jolie Ville Kings Island Luxor',
      type: '5-Star Island Resort',
      desc: 'Unique resort on Kings Island in the middle of the Nile. Accessed by hotel boat. Lush banana plantations, free-roaming peacocks, and a magical escape from the city. One of Luxor\'s most unique stays.',
      area: 'Kings Island, Nile River, Luxor',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 5200, price_usd_night: 98,
      phone: '+20 95 227 4855',
      website: 'https://www.maritim.com',
      rating: 4.6,
      verified: true,
      features: ['Private island', 'Hotel boat', 'Tropical gardens', 'Pool', 'WiFi', 'Peacock sanctuary', 'Fine dining'],
      photos: [
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
        'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=800&q=80',
        'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80',
      ],
      faq: [{ q: 'How do I get to the island?', a: 'The hotel boat runs every 15 minutes from the Corniche dock. 5-minute crossing.' }],
    },
  ],
  aswan: [
    {
      name: 'Sofitel Old Cataract Aswan',
      type: '5-Star Historic Luxury',
      desc: 'The grandest hotel in Egypt. Built in 1899, Agatha Christie wrote Death on the Nile here. Pink sandstone palace on a granite outcrop above the Nile. The terrace view is one of the most beautiful in the world.',
      area: 'Abtal El Tahrir, Corniche',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 17000, price_usd_night: 319,
      phone: '+20 97 231 6000',
      website: 'https://all.accor.com',
      rating: 4.9,
      verified: true,
      features: ['1899 historic palace', 'Agatha Christie suite', 'Infinity pool', 'Nile panorama terrace', 'Spa', 'Fine dining', 'WiFi'],
      photos: [
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Old_Cataract_Hotel_Aswan.jpg/960px-Old_Cataract_Hotel_Aswan.jpg',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1568322445389-f64ac2515020?w=800&q=80',
      ],
      faq: [{ q: 'Can I visit just for tea or drinks?', a: 'Yes — the afternoon tea terrace is open to non-guests (450–700 EGP). Worth every pound for the view.' }],
    },
    {
      name: 'Movenpick Resort Aswan',
      type: '5-Star Island Resort',
      desc: 'Swiss-managed 5-star on Elephantine Island. Reached by hotel motorboat from Corniche. One of the finest settings in Egypt — surrounded by the Nile with views of the Old Cataract and granite boulders.',
      area: 'Elephantine Island, Aswan',
      checkin: '15:00', checkout: '12:00',
      price_egp_night: 6500, price_usd_night: 122,
      phone: '+20 97 230 3455',
      website: 'https://www.movenpick.com',
      rating: 4.8,
      verified: true,
      features: ['Elephantine Island', 'Hotel boat access', 'Pool', 'Spa', 'WiFi', 'Fine dining', 'Nile views from every room'],
      photos: [
        'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&q=80',
        'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&q=80',
        'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Tolip Aswan Hotel',
      type: '4-Star Hotel',
      desc: 'Modern 4-star on the Aswan Corniche with excellent Nile views. Reliable service, comfortable rooms, and good value for a prime riverside location. Popular with tour groups and independent travelers.',
      area: 'Corniche El Nil, Aswan',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 3500, price_usd_night: 66,
      phone: '+20 97 231 2020',
      website: 'https://www.toliphotels.com',
      rating: 4.3,
      verified: true,
      features: ['Nile view', 'Pool', 'Breakfast included', 'WiFi', 'Restaurant', 'Central location', 'Corniche access'],
      photos: [
        'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
        'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=800&q=80',
        'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80',
      ],
      faq: [],
    },
    {
      name: 'Pyramisa Island Hotel Aswan',
      type: '5-Star Island Resort',
      desc: 'Resort hotel on its own island in the middle of the Nile. Reached by hotel motorboat. 360° Nile views. Large grounds, multiple pools. Quiet and self-contained — feels like a private island escape.',
      area: 'Isis Island, Aswan Nile',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 4800, price_usd_night: 90,
      phone: '+20 97 231 7400',
      website: 'https://www.pyramisa.com',
      rating: 4.5,
      verified: true,
      features: ['Private island', 'Hotel boat access', 'Multiple pools', 'Nile panorama', 'WiFi', 'Spa', 'Tennis'],
      photos: [
        'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
        'https://images.unsplash.com/photo-1540541338287-41700207dee6?w=800&q=80',
        'https://images.unsplash.com/photo-1568084680786-a84f91d1153c?w=800&q=80',
      ],
      faq: [{ q: 'How do I get to the island?', a: 'The hotel operates a motorboat from the Corniche. Runs every 20 min during the day.' }],
    },
    {
      name: 'Basma Hotel Aswan',
      type: '4-Star Resort',
      desc: 'Best value 4-star in Aswan. Hillside location with panoramic Nile views from every room. Large pool, excellent breakfast, reliable service. Walking distance from all major sites.',
      area: 'Abtal El Tahrir, near Old Cataract',
      checkin: '14:00', checkout: '12:00',
      price_egp_night: 4000, price_usd_night: 75,
      phone: '+20 97 231 0901',
      website: 'https://www.basmahotel.com',
      rating: 4.6,
      verified: true,
      features: ['Nile panorama', 'Large pool', 'Breakfast included', 'WiFi', 'Walking distance to Corniche', 'Good restaurant'],
      photos: [
        'https://images.unsplash.com/photo-1588880331179-bc9b93a8cb5e?w=800&q=80',
        'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
        'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&q=80',
      ],
      faq: [],
    },
  ],
};